import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
test('accounts, authoritative combat, actual leaderboard, PvP and restart persistence',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'cyper-test-')),port=32000+Math.floor(Math.random()*2000),base=`http://127.0.0.1:${port}`;
 let server;
 async function start(){server=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),CYPER_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error('Server exited '+code)));});}
 async function stop(){if(server){const done=once(server,'exit');server.kill();await done;server=null;}}
 async function req(route,data,cookie){const r=await fetch(base+route,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};}
 try{await start();assert.equal((await fetch(base+'/.data/players.json')).status,404);assert.equal((await fetch(base+'/.git/config')).status,404);assert.equal((await req('/api/me')).status,401);
 const password='test-password-123';const first=await req('/api/register',{username:'runner_one',password}),second=await req('/api/register',{username:'runner_two',password});assert.equal(first.status,200);assert.equal(second.status,200);const cookie=first.cookie;
 // Existing purchased balance fixture; top-up authorization is covered separately.
 await stop();const paid=JSON.parse(await readFile(path.join(directory,'players.json'),'utf8'));paid.users[0].state.units=3;await writeFile(path.join(directory,'players.json'),JSON.stringify(paid));await start();
 assert.equal((await req('/api/login',{username:'runner_one',password:'incorrect-password'})).status,401);assert.equal((await req('/api/register',{username:'runner_one',password})).status,409);
 assert.equal((await req('/api/action',{action:'cheat',credits:999999},cookie)).status,400);assert.equal((await req('/api/action',{action:'buy',id:'gear199',black:true},cookie)).status,400);
 assert.equal((await req('/api/action',{action:'accept',id:'quest0'},cookie)).status,200);
 for(let i=0;i<2;i++){let r=await req('/api/action',{action:'fight'},cookie);assert.equal(r.status,200);while(r.data.state.combat){r=await req('/api/action',{action:'attack'},cookie);assert.equal(r.status,200);}}
 const claimed=await req('/api/action',{action:'claim',id:'quest0'},cookie);assert.equal(claimed.data.state.level,2);assert.equal((await req('/api/action',{action:'claim',id:'quest0'},cookie)).status,400);
 const enhanced=await req('/api/action',{action:'upgrade',id:'gear0'},cookie);assert.equal(enhanced.data.state.calibration.gear0.level,1);
 const fitted=await req('/api/action',{action:'module',id:'gear0',slot:0,module:'damage'},cookie);assert.equal(fitted.status,200);assert.equal(fitted.data.state.calibration.gear0.modules[0],'damage');assert.equal((await req('/api/action',{action:'module',id:'gear0',slot:2,module:'health'},cookie)).status,400);
 assert.equal((await req('/api/action',{action:'exchange',direction:'sell',amount:1},cookie)).status,400);assert.equal((await req('/api/action',{action:'exchange',direction:'buy',amount:1},cookie)).status,400);
 const printed=await req('/api/action',{action:'print',id:'implant'},cookie);assert.equal(printed.status,200);assert.equal(printed.data.state.printing.total,1);assert.equal(printed.data.state.scrap,6);
 const calibrated=await req('/api/action',{action:'calibrate',id:'gear0',boost:true,protect:true,success:1,level:99},cookie);assert.equal(calibrated.status,200);assert.equal(calibrated.data.state.calibration.gear0.level,2);assert.equal(calibrated.data.state.units,0);
 assert.equal((await req('/api/action',{action:'bank',direction:'deposit',amount:50},cookie)).status,200);assert.equal((await req('/api/action',{action:'bank',direction:'deposit',amount:0.5},cookie)).status,400);
 assert.equal((await req('/api/rank')).data.players.length,2);await req('/api/action',{action:'rest'},cookie);let duel=await req('/api/action',{action:'pvp',id:second.data.user.id},cookie);assert.equal(duel.data.state.combat.name,'runner_two');while(duel.data.state.combat)duel=await req('/api/action',{action:'attack'},cookie);const outcome={wins:duel.data.state.wins,losses:duel.data.state.losses};assert.equal(outcome.wins+outcome.losses,1);assert((await req('/api/rank')).data.players.some(p=>p.name==='runner_one'));
 await req('/api/action',{action:'rest'},cookie);assert.equal((await req('/api/action',{action:'enter-dungeon'},cookie)).status,200);assert.equal((await req('/api/action',{action:'dungeon-step',id:'teleport',x:13,y:1},cookie)).status,400);assert.equal((await req('/api/action',{action:'rest'},cookie)).status,400);assert.equal((await req('/api/action',{action:'dungeon-step',id:'left'},cookie)).status,200);const encounter=await req('/api/action',{action:'dungeon-step',id:'left'},cookie);assert.equal(encounter.status,200);assert.equal(encounter.data.state.combat.dungeonTile,230);assert.equal((await req('/api/action',{action:'leave-dungeon'},cookie)).status,400);
 const stored=JSON.parse(await readFile(path.join(directory,'players.json'),'utf8'));assert(!JSON.stringify(stored).includes(password));assert.equal(stored.users[0].state.wins,outcome.wins);
 await stop();await start();assert.equal((await req('/api/me',null,cookie)).status,200);const login=await req('/api/login',{username:'runner_one',password});assert.equal(login.status,200);assert.equal(login.data.state.wins,outcome.wins);assert.equal(login.data.state.losses,outcome.losses);assert.equal(login.data.state.level,2);assert.equal(login.data.state.calibration.gear0.modules[0],'damage');assert.equal(login.data.state.calibration.gear0.level,2);assert.equal(login.data.state.printing.total,1);assert.equal(login.data.state.bank,50);assert.equal(login.data.state.units,0);assert.equal(login.data.state.dungeon.x,5);assert.equal(login.data.state.dungeon.floor,1);assert.equal(login.data.state.combat.dungeonTile,230);let battle=login;while(battle.data.state.combat)battle=await req('/api/action',{action:'attack'},login.cookie);assert.equal(battle.data.state.dungeon.cells[230],'.');assert.equal((await req('/api/action',{action:'leave-dungeon'},login.cookie)).status,200);assert.equal((await req('/api/logout',{},login.cookie)).status,200);assert.equal((await req('/api/me',null,login.cookie)).status,401);
 }finally{await stop();await rm(directory,{recursive:true,force:true});}
});
