import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
test('settings persist with server validation; password/name-confirmed deletion revokes every session and preserves other players',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'cyper-settings-test-')),port=47000+Math.floor(Math.random()*1000),base=`http://127.0.0.1:${port}`,file=path.join(directory,'players.json');let server;
 async function start(){server=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),CYPER_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',n=>reject(new Error('Exit '+n)));});}
 async function stop(){if(server){const done=once(server,'exit');server.kill();await done;server=null;}}
 async function req(route,data,cookie,extra={}){const r=await fetch(base+route,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...extra},...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:r.headers.get('content-type')?.includes('application/json')?await r.json():await r.text()};}
 const password='settings-test-password';let a,b,a2;
 const act=(body,cookie=a.cookie)=>req('/api/action',body,cookie);
 try{
  await start();assert.equal((await req('/api/account/delete',{confirm:true,confirmName:'none',password})).status,401);a=await req('/api/register',{username:'settings_alpha',password});b=await req('/api/register',{username:'settings_beta',password});await stop();const fixture=JSON.parse(await readFile(file,'utf8'));fixture.users[0].state.credits=2000;await writeFile(file,JSON.stringify(fixture));await start();a=await req('/api/login',{username:'settings_alpha',password});b=await req('/api/login',{username:'settings_beta',password});a2=await req('/api/login',{username:'settings_alpha',password});
  const initial=(await req('/api/me',null,a.cookie)).data.state;assert.equal((await act({action:'settings',values:{music:true,credits:999999}})).status,400);assert.deepEqual((await req('/api/me',null,a.cookie)).data.state,initial);assert.equal((await act({action:'settings',values:{musicVolume:'75'}})).status,400);assert.equal((await act({action:'settings',values:{translateChat:true}})).status,400);
  assert.equal((await act({action:'settings',values:{uiSize:'large',language:'en',music:true,musicVolume:35,privateBadges:false,hideHandler:true,hideDonations:true,disableVictory:true}})).status,200);assert.equal((await req('/api/profile/'+a.data.user.id)).data.assets.name,'Runner ẩn danh');assert.equal((await act({action:'name',id:'SafeRunner'})).status,200);
  for(const body of [{action:'buy',id:'gear2'},{action:'upgrade',id:'gear2'},{action:'module',id:'gear2',slot:0,module:'health'},{action:'market-list',id:'gear2',price:100},{action:'corp-create',text:'Deletion Test Guild'},{action:'donate',id:'global',amount:100}])assert.equal((await act(body)).status,200);
  let world=(await req('/api/world',null,a.cookie)).data;assert.equal(world.funds[0].total,100);assert.equal(world.funds[0].contributors.length,0);assert.equal((await act({action:'corp-join',id:world.corporation},b.cookie)).status,200);assert.equal((await act({action:'chat',channel:'guild',text:'deleted guild message'})).status,200);world=(await req('/api/world',null,b.cookie)).data;assert.equal((await act({action:'chat',channel:'guild',replyId:world.guildMessages[0].id,text:'keep this reply'},b.cookie)).status,200);assert.equal((await act({action:'mail-send',id:b.data.user.id,text:'deleted mail'})).status,200);
  await stop();await start();a=await req('/api/login',{username:'settings_alpha',password});a2=await req('/api/login',{username:'settings_alpha',password});b=await req('/api/login',{username:'settings_beta',password});assert.equal(a.data.state.settings.musicVolume,35);assert.equal(a.data.state.settings.uiSize,'large');assert.equal(a.data.state.privacy.badges,true);
  for(const data of [{confirm:true,confirmName:'settings_alpha',password},{confirmName:'SafeRunner',password}])assert.equal((await req('/api/account/delete',data,a.cookie)).status,400);assert.equal((await req('/api/account/delete',{confirm:true,confirmName:'SafeRunner',password:'wrong-password'},a.cookie)).status,403);assert.equal((await req('/api/account/delete',{confirm:true,confirmName:'SafeRunner',password},a.cookie,{Origin:'https://untrusted.invalid'})).status,403);assert.equal((await req('/api/me',null,a.cookie)).status,200);
  assert.equal((await act({action:'work-start',id:'printing'})).status,200);assert.equal((await req('/api/account/delete',{confirm:true,confirmName:'SafeRunner',password},a.cookie)).status,400);assert.equal((await act({action:'work-cancel'})).status,200);
  const originalB=(await req('/api/me',null,b.cookie)).data.state,deleted=await req('/api/account/delete',{confirm:true,confirmName:'SafeRunner',password,id:b.data.user.id},a.cookie);assert.equal(deleted.status,200);assert.equal(deleted.cookie,'cyper_session=');for(const cookie of [a.cookie,a2.cookie])assert.equal((await req('/api/me',null,cookie)).status,401);assert.deepEqual((await req('/api/me',null,b.cookie)).data.state,originalB);assert.equal((await req('/api/profile/'+a.data.user.id)).status,404);
  world=(await req('/api/world',null,b.cookie)).data;assert.equal(world.market.length,0);assert.equal(world.mail.length,0);assert.equal(world.guildMessages.length,1);assert.equal(world.guildMessages[0].reply,undefined);assert.equal(world.corporations[0].leader,b.data.user.id);assert.equal(world.funds[0].total,100);
  const saved=JSON.parse(await readFile(file,'utf8'));assert.equal(saved.users.length,1);assert.equal(saved.users[0].id,b.data.user.id);await stop();await start();assert.equal((await req('/api/login',{username:'settings_alpha',password})).status,401);const restored=await req('/api/login',{username:'settings_beta',password});assert.equal(restored.status,200);assert.equal((await req('/api/world',null,restored.cookie)).data.corporations[0].leader,b.data.user.id);
  assert.equal((await req('/src/account-data.js')).status,404);assert.equal((await req('/src/settings.js')).status,200);assert.equal((await req('/src/audio.js')).status,200);
 }finally{await stop();await rm(directory,{recursive:true,force:true});}
});
