export const adminLabels = {ban: 'Khóa tài khoản', unban: 'Gỡ khóa', mute: 'Cấm chat/thư',
  unmute: 'Gỡ cấm chat', grant: 'Hỗ trợ tài nguyên', 'delete-message': 'Xóa tin nhắn',
  'cancel-listing': 'Thu hồi tin rao', announce: 'Thông báo server', maintenance: 'Bảo trì'};

export function adminView({online, data, section, query, pending, esc, button}) {
  if (!online?.admin) return '<p class="hint">Chỉ tài khoản admin được mở bảng quản trị.</p>';
  const prepare = (label, action, id = '', target = '') => `<button data-action="admin-prepare" data-kind="${action}" data-id="${esc(id)}" data-label="${esc(target)}">${label}</button>`;
  const time = value => value ? new Date(value).toLocaleString('vi', {timeZone: 'Asia/Ho_Chi_Minh'}) : '—';
  const tabs = [['players', 'Người chơi'], ['chat', 'Chat'], ['market', 'Chợ'], ['system', 'Server'], ['audit', 'Nhật ký']];
  const heading = `<section class="admin-screen"><div class="admin-heading"><div><small>SERVER AUTHORITY</small><h1>Bảng quản trị</h1><p>Quản lý thế giới Neon · ${esc(online.name)}</p></div>${button('Làm mới', 'admin-refresh')}</div><div class="admin-tabs">${tabs.map(([id, label]) => `<button data-action="admin-tab" data-id="${id}" class="${section === id ? 'selected' : ''}">${label}</button>`).join('')}</div>`;
  if (!data) return heading + '<p class="hint">Chưa tải dữ liệu. Bấm Làm mới để thử lại.</p></section>';
  const stats = `<div class="admin-stats">${[['TÀI KHOẢN', data.stats.players], ['BỊ KHÓA', data.stats.banned], ['TIN RAO', data.stats.listings], ['PHÒNG DUNGEON', data.stats.rooms]].map(([label, value]) => `<div><small>${label}</small><b>${value}</b></div>`).join('')}</div>`;
  const form = pending ? `<form id="admin-action-form" class="admin-action-form" data-kind="${pending.action}" data-id="${esc(pending.id || '')}"><div class="section-label">${adminLabels[pending.action]} ${pending.label ? '· ' + esc(pending.label) : ''}</div>
    ${['ban', 'mute'].includes(pending.action) ? `<label>Thời hạn (giờ)${pending.action === 'ban' ? ' · 0 = vô thời hạn' : ''}<input name="hours" type="number" min="${pending.action === 'ban' ? 0 : 1}" max="${pending.action === 'ban' ? 8760 : 720}" value="24" required></label>` : ''}
    ${pending.action === 'grant' ? '<label>Tài nguyên<select name="resource"><option value="credits">Credits</option><option value="units">Unit</option><option value="scrap">Linh kiện</option></select></label><label>Số lượng<input name="amount" type="number" min="1" max="1000000" value="100" required></label>' : ''}
    ${pending.action === 'announce' ? `<label>Thông báo (để trống để gỡ)<textarea name="text" rows="3" maxlength="500">${esc(data.announcement?.text || '')}</textarea></label>` : ''}
    ${pending.action === 'maintenance' ? `<label>Trạng thái<select name="enabled"><option value="true" ${data.maintenance ? 'selected' : ''}>Bật bảo trì</option><option value="false" ${!data.maintenance ? 'selected' : ''}>Tắt bảo trì</option></select></label>` : ''}
    <label>Lý do<input name="reason" minlength="5" maxlength="200" placeholder="Lý do để ghi nhật ký" required></label><label>Mật khẩu admin<input name="password" type="password" autocomplete="current-password" minlength="8" maxlength="128" required></label><p class="hint">Thao tác được ghi nhật ký. Mật khẩu không được lưu trong trình duyệt.</p><div class="actions"><button type="submit">Xác nhận thao tác</button><button type="button" data-action="admin-cancel">Hủy</button></div></form>` : '';
  let content = '';
  if (section === 'players') content = `<form id="admin-search-form" class="admin-search"><input name="query" value="${esc(query)}" maxlength="80" aria-label="Tìm tài khoản" placeholder="Tài khoản, bí danh hoặc ID"><button>Tìm</button></form><p class="hint">${data.matches} kết quả · Trang ${data.page + 1}/${data.pages}</p><div class="admin-list">${data.players.map(u => `<article><div class="admin-row-title"><b>${esc(u.name)}</b><span>${u.admin ? 'ADMIN' : u.banned ? 'BỊ KHÓA' : 'RUNNER'}</span></div><p>${esc(u.username)} · LV ${u.level} · ${u.credits.toLocaleString('vi')} ₡</p><small>${esc(u.id)} · ${esc(u.map)} · ${u.busy ? 'Đang hoạt động' : 'Rảnh'}</small><p>Unit ${u.units} · Linh kiện ${u.scrap}${u.banned ? '<br>Khóa đến: ' + (u.banUntil === 0 ? 'Vô thời hạn' : time(u.banUntil)) : ''}${u.muteUntil > data.now ? '<br>Cấm chat đến: ' + time(u.muteUntil) : ''}</p><div class="actions">${u.admin ? '' : prepare(u.banned ? 'Gỡ khóa' : 'Khóa', u.banned ? 'unban' : 'ban', u.id, u.username) + prepare(u.muteUntil > data.now ? 'Gỡ cấm chat' : 'Cấm chat', u.muteUntil > data.now ? 'unmute' : 'mute', u.id, u.username)}${prepare('Hỗ trợ', 'grant', u.id, u.username)}</div></article>`).join('') || '<p class="hint">Không có tài khoản phù hợp.</p>'}</div><div class="pagination">${button('‹ Trước', 'admin-page', String(data.page - 1), !data.page)}<span>${data.page + 1}/${data.pages}</span>${button('Sau ›', 'admin-page', String(data.page + 1), data.page + 1 >= data.pages)}</div>`;
  if (section === 'chat') content = '<p class="hint">100 tin gần nhất trong chat toàn cầu/tập đoàn. Thư riêng không hiển thị ở đây.</p><div class="admin-list">' + data.messages.map(m => `<article><b>${esc(m.name)}</b><small>${esc(m.channel)} · ${time(m.time)}</small><p>${esc(m.text || m.item || '')}</p>${prepare('Xóa tin', 'delete-message', m.id, m.name)}</article>`).join('') + '</div>';
  if (section === 'market') content = '<p class="hint">100 tin rao mới nhất. Thu hồi trả đồ cùng nâng cấp/module cho người bán; túi đầy gửi hộp thư. Người bán cần kết thúc dungeon/giao tranh trước.</p><div class="admin-list">' + data.listings.map(m => `<article><b>${esc(m.name)}</b><p>${esc(m.sellerName)} · ${m.price.toLocaleString('vi')} ₡</p>${prepare('Thu hồi', 'cancel-listing', m.id, m.sellerName)}</article>`).join('') + '</div>';
  if (section === 'system') content = `<div class="admin-list"><article><b>TRẠNG THÁI SERVER</b><p>Lưu trữ: ${esc(data.stats.mode)} · ${data.stats.content} hồ sơ nội dung</p><p>${data.stats.sessions} phiên còn hạn (không phải số người đang online).</p><p>Bảo trì: ${data.maintenance ? 'ĐANG BẬT' : 'TẮT'}</p>${prepare('Đổi trạng thái', 'maintenance')}</article><article><b>THÔNG BÁO</b><p>${esc(data.announcement?.text || 'Chưa có thông báo.')}</p>${prepare('Soạn / gỡ thông báo', 'announce')}</article></div>`;
  if (section === 'audit') content = '<p class="hint">100 thao tác gần nhất; server giữ tối đa 1.000 bản ghi.</p><div class="admin-list">' + data.audit.map(a => `<article><b>${esc(adminLabels[a.action] || a.action)}</b><small>${time(a.time)} · ${esc(a.actorName)}</small><p>${esc(a.reason)}</p><small>Đích: ${esc(a.target || 'Server')}</small><pre>${esc(JSON.stringify(a.details))}</pre></article>`).join('') + '</div>';
  return heading + stats + form + content + '</section>';
}
