import {gear,rarities} from './content.js';
import {earnedBadges} from './achievements.js';
import {note} from './game.js';
import {cosmetics} from './city.js';
export const shelves=[{level:100,price:1000000},{level:200,price:5000000},{level:300,price:25000000}];
export const pets=[{id:'orb',name:'Drone Mắt Quỹ Đạo',level:1,price:120,icon:'◉'},{id:'cat',name:'Mèo máy Pixel',level:10,price:500,icon:'🐈'},{id:'jelly',name:'Sứa ánh sáng',level:20,price:1500,icon:'♧'}];
export const privacy=s=>({showcases:true,pets:true,badges:false,chatSkin:false,...s.privacy});
export function publicAssets(s){const p=privacy(s);return {
 name:s.settings?.hideHandler?'Runner ẩn danh':s.name,level:s.level,
 showcases:p.showcases?(s.showcases||[]).map(id=>gear.find(g=>g.id===id&&(s.inventory.includes(id)||s.housing?.storage?.includes(id)))).map(g=>g?{id:g.id,name:g.name,level:g.level,rarity:g.rarity}:null):null,
 pets:p.pets?pets.filter(v=>s.pets?.includes(v.id)).map(v=>({id:v.id,name:v.name,icon:v.icon,active:s.pet===v.id})):null,
 badges:p.badges?earnedBadges(s).map(v=>({id:v.id,name:v.name,icon:v.icon})):null,
 chatSkin:p.chatSkin?cosmetics.find(c=>c.id===s.chatSkin&&s.cosmetics?.includes(c.id))?.id||null:null
};}
export function assetAction(s,b){
 if(b.action==='privacy'){if(!['showcases','pets','badges','chatSkin'].includes(b.id)||typeof b.visible!=='boolean')return false;s.privacy={...privacy(s),[b.id]:b.visible};return true;}
 if(s.combat||s.dungeon)return false;
 if(b.action==='shelf-unlock'){const i=Number(b.id),v=shelves[i];if(!['0','1','2'].includes(String(b.id))||!v||s.shelfUnlocks?.includes(i)||s.level<v.level||s.credits<v.price)return false;s.credits-=v.price;(s.shelfUnlocks??=[]).push(i);note(s,`Mở kệ trưng bày ${i+1}.`);return true;}
 if(b.action==='shelf-set'){if(!Number.isInteger(b.slot)||b.slot<0||b.slot>2||!s.shelfUnlocks?.includes(b.slot))return false;if(b.id&&(!gear.some(g=>g.id===b.id)||!(s.inventory.includes(b.id)||s.housing?.storage?.includes(b.id))))return false;s.showcases??=[null,null,null];s.showcases[b.slot]=b.id||null;return true;}
 if(b.action==='pet-buy'){const v=pets.find(v=>v.id===b.id);if(!v||s.pets?.includes(v.id)||s.level<v.level||s.credits<v.price)return false;s.credits-=v.price;(s.pets??=[]).push(v.id);s.pet=v.id;note(s,`Nhận thú cưng ${v.name}.`);return true;}
 if(b.action==='pet-select'){if(b.id&&!s.pets?.includes(b.id))return false;s.pet=b.id||null;return true;}
 if(b.action==='chat-skin'){if(b.id&&!s.cosmetics?.includes(b.id))return false;s.chatSkin=b.id||null;return true;}
 return false;
}
export function assetsView({s,esc,button}){
 const p=privacy(s),ownPets=pets.filter(v=>s.pets?.includes(v.id)),badges=earnedBadges(s),selectItems=gear.filter(g=>s.inventory.includes(g.id)||s.housing?.storage?.includes(g.id));
 const setting=(id,name)=>`<label class="privacy-setting"><span>${name}</span><input type="checkbox" data-privacy="${id}" ${p[id]?'checked':''}></label>`;
 return `<div class="section-label">KỆ HIỂN THỊ <span>${s.shelfUnlocks?.length||0} / 3</span></div><div class="showcase-list">${shelves.map((v,i)=>s.shelfUnlocks?.includes(i)?`<article class="showcase"><small>KỆ ${i+1} · ĐÃ MỞ</small><form class="asset-form" data-kind="shelf-set" data-slot="${i}"><select name="id" aria-label="Trang bị trưng bày kệ ${i+1}"><option value="">Kệ trống</option>${selectItems.map(g=>`<option value="${g.id}" ${s.showcases?.[i]===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select><button>Trưng bày</button></form></article>`:`<article class="showcase locked"><div><small>YÊU CẦU LV ${v.level}</small><b class="pink">BẠN ĐANG Ở LV ${s.level}</b><small>GIÁ ${v.price.toLocaleString('vi')} CREDITS</small></div>${button('◇ Mở kệ','shelf-unlock',String(i),s.level<v.level||s.credits<v.price)}<span>SLOT ĐÃ KHÓA</span></article>`).join('')}</div>${setting('showcases','Công khai kệ trưng bày')}<div class="section-label">THÚ CƯNG <span>${ownPets.length}</span></div>${!ownPets.length?'<p class="asset-empty">BẠN CHƯA CÓ THÚ CƯNG</p>':''}<div class="pet-list">${pets.map(v=>`<article class="pet-card"><span class="pet-icon">${v.icon}</span><div><b>${v.name}</b><small>LV ${v.level} · Bạn đồng hành trang trí</small></div>${s.pets?.includes(v.id)?button(s.pet===v.id?'Đang đi cùng':'Chọn','pet-select',v.id,s.pet===v.id):button(`${v.price.toLocaleString('vi')} ₡`,'pet-buy',v.id,s.level<v.level||s.credits<v.price)}</article>`).join('')}</div>${s.pet?button('Cho thú cưng nghỉ','pet-select',''):''}${setting('pets','Công khai thú cưng')}<div class="section-label">HUY HIỆU <span>${badges.length}</span></div><div class="asset-badges">${badges.map(v=>`<span title="${esc(v.name)}">${v.icon} ${v.name}</span>`).join('')||'<p class="asset-empty">HOÀN THÀNH THỬ THÁCH ĐỂ NHẬN HUY HIỆU</p>'}</div>${setting('badges','Công khai huy hiệu')}<div class="section-label">SKIN CHAT</div><form class="asset-form" data-kind="chat-skin"><select name="id" aria-label="Skin chat"><option value="">Mặc định</option>${cosmetics.filter(v=>s.cosmetics?.includes(v.id)).map(v=>`<option value="${v.id}" ${s.chatSkin===v.id?'selected':''}>${v.name}</option>`).join('')}</select><button>Lưu skin</button></form>${setting('chatSkin','Hiển thị skin trong chat và hồ sơ công khai')}${button('Mua cyberwear','nav','cosmetics')}<p class="hint">Quyền riêng tư áp dụng cho hồ sơ công khai trên server. Thú cưng và kệ trưng bày không cộng chỉ số chiến đấu.</p>`;
}
export function publicAssetsView(a,esc){return `<div class="section-label">TÀI SẢN CÔNG KHAI / ${esc(a.name)}</div>${[['KỆ TRƯNG BÀY',a.showcases?.filter(Boolean).map(g=>`${g.name} · LV ${g.level} / ${rarities[g.rarity]}`)],['THÚ CƯNG',a.pets?.map(v=>`${v.icon} ${v.name}${v.active?' · Đang đi cùng':''}`)],['HUY HIỆU',a.badges?.map(v=>`${v.icon} ${v.name}`)]].map(([label,list])=>`<article class="showcase"><small>${label}</small>${list===undefined?'<p class="asset-empty">THÔNG TIN ĐƯỢC ĐẶT RIÊNG TƯ</p>':list.length?list.map(t=>`<p>${esc(t)}</p>`).join(''):'<p class="asset-empty">CHƯA CÓ VẬT PHẨM</p>'}</article>`).join('')}<p class="hint">LV ${a.level} · Skin chat: ${esc(cosmetics.find(v=>v.id===a.chatSkin)?.name||'Mặc định / riêng tư')}</p>`;}
