import {platformStatus} from './platform.js';

const googleIcon = '<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285f4" d="M21.6 12.23c0-.71-.06-1.39-.18-2.05H12v3.88h5.38a4.6 4.6 0 0 1-2 3.02v2.52h3.24c1.9-1.75 2.98-4.32 2.98-7.37Z"/><path fill="#34a853" d="M12 22c2.7 0 4.96-.9 6.62-2.4l-3.24-2.52c-.9.6-2.05.96-3.38.96-2.6 0-4.8-1.75-5.59-4.1H3.07v2.6A10 10 0 0 0 12 22Z"/><path fill="#fbbc05" d="M6.41 13.94A6 6 0 0 1 6.1 12c0-.67.11-1.32.31-1.94v-2.6H3.07A10 10 0 0 0 2 12c0 1.62.39 3.15 1.07 4.54l3.34-2.6Z"/><path fill="#ea4335" d="M12 5.96c1.47 0 2.79.51 3.82 1.51l2.86-2.86A9.58 9.58 0 0 0 12 2a10 10 0 0 0-8.93 5.46l3.34 2.6A5.97 5.97 0 0 1 12 5.96Z"/></svg>';
export function googleAvailable(providers) {
  return !!providers?.google?.enabled && (!platformStatus().native || !!providers.google.native);
}
export function accountSecurityView({online, providers, esc, pending = false}) {
  if (!online) return '';
  const password = online.auth?.password !== false, linked = !!online.auth?.google;
  const enabled = googleAvailable(providers);
  return `<section class="account-security"><div class="section-label">ĐĂNG NHẬP VÀ BẢO MẬT</div><p>Tên đăng nhập: <b>${esc(online.username || online.name)}</b></p><div class="auth-methods"><span>${password?'Mật khẩu đã tạo':'Chưa có mật khẩu'}</span><span>${linked?'Google đã liên kết':'Chưa liên kết Google'}</span></div>${!linked&&password?`<details data-ui-panel="google-link"><summary>Liên kết Google với nhân vật này</summary><p>Giữ tiến trình hiện tại. Xác nhận mật khẩu, sau đó chọn Google của bạn.</p><form id="google-link-form"><input name="password" type="password" autocomplete="current-password" placeholder="Mật khẩu hiện tại" aria-label="Mật khẩu xác nhận liên kết Google" required minlength="8" maxlength="128" ${enabled&&!pending?'':'disabled'}><button class="google-signin" ${enabled&&!pending?'':'disabled'}>${googleIcon}<span>Liên kết với Google</span></button></form>${!enabled?'<p class="hint">Server chưa bật Google, hoặc app cần địa chỉ server HTTPS.</p>':''}</details>`:''}<details data-ui-panel="account-password" ${password?'':'open'}><summary>${password?'Đổi mật khẩu':'Tạo mật khẩu'}</summary><p>${password?'Mật khẩu mới dùng để đăng nhập và xác nhận thao tác tài khoản.':'Tạo mật khẩu sau khi đăng nhập Google để có thêm cách đăng nhập và xác nhận xóa tài khoản. Thực hiện trong năm phút sau lần đăng nhập Google.'}</p><form id="account-password-form"><input name="username" autocomplete="username" value="${esc(online.username||online.name)}" readonly aria-label="Tên tài khoản">${password?'<input name="currentPassword" type="password" autocomplete="current-password" placeholder="Mật khẩu hiện tại" aria-label="Mật khẩu hiện tại" required minlength="8" maxlength="128">':''}<input name="newPassword" type="password" autocomplete="new-password" placeholder="Mật khẩu mới (ít nhất 8 ký tự)" aria-label="Mật khẩu mới" required minlength="8" maxlength="128"><input name="confirmPassword" type="password" autocomplete="new-password" placeholder="Nhập lại mật khẩu mới" aria-label="Nhập lại mật khẩu mới" required minlength="8" maxlength="128"><button ${pending?'disabled':''}>${password?'Lưu mật khẩu mới':'Tạo mật khẩu'}</button></form><p class="hint">Lưu mật khẩu sẽ thu hồi các phiên khác; phiên đang dùng được giữ lại.</p></details></section>`;
}
export function authenticationView({s, online, providers, esc, button, pending = false}) {
  const enabled = googleAvailable(providers), p = platformStatus();
  const hint = !p.connected ? 'Cần có mạng để đăng nhập.' : p.native&&!p.server ? 'Thêm địa chỉ server trong Cài đặt để đăng nhập.' :
    !providers?.google?.enabled ? 'Google chưa được bật trên server. Bạn vẫn có thể dùng tài khoản và mật khẩu.' :
      p.native&&!providers.google.native ? 'Đăng nhập Google trên app cần server HTTPS.' : 'Google lần đầu tạo nhân vật online mới. Để giữ nhân vật cũ, đăng nhập tài khoản cũ rồi liên kết Google.';
  if (online) return `<div class="hero"><div class="eyebrow">SERVER SESSION</div><h1>${esc(s.name)}</h1><p>Nhân vật lưu trên server. Dùng cùng tài khoản trên các thiết bị để tiếp tục.</p>${button('Đăng xuất','logout')}</div>`+accountSecurityView({online,providers,esc,pending});
  return `<div class="hero auth-hero"><div class="eyebrow">KẾT NỐI SERVER</div><h1>Vào mạng.<br><span>Giữ danh tính.</span></h1><p>Đăng nhập để lưu nhân vật và chơi cùng cộng đồng. Tiến trình khách và online được lưu riêng.</p><button class="google-signin" data-action="google-login" ${enabled&&p.connected&&!pending?'':'disabled'}>${googleIcon}<span>${pending?'Đang chờ Google…':'Tiếp tục với Google'}</span></button>${pending?button('Hủy đăng nhập Google','google-cancel'):''}<p class="hint google-hint">${hint}</p><div class="auth-divider"><span>HOẶC DÙNG TÀI KHOẢN</span></div><form id="auth-form"><input name="username" placeholder="Tên tài khoản" aria-label="Tên tài khoản" autocomplete="username" pattern="[a-zA-Z0-9_]{3,24}" required maxlength="24"><input name="password" type="password" placeholder="Mật khẩu (ít nhất 8 ký tự)" aria-label="Mật khẩu" autocomplete="current-password" minlength="8" maxlength="128" required><div class="actions"><button name="mode" value="login" ${pending?'disabled':''}>Đăng nhập</button><button name="mode" value="register" ${pending?'disabled':''}>Tạo tài khoản</button></div></form></div>`;
}
