import {cityIcon} from './city-icons.js';
import {pets} from './assets.js';
import {maps} from './content.js';
import {communityView} from './world-view.js';
export const cityBanner=(title,description,badge,scene='bazaar')=>`<div class="district-banner"><img src="/src/${scene}.svg" alt="${scene==='coast'?'Bờ biển Neon với bến tàu và đèn dẫn đường':'Phố chợ Neon với các gian hàng công nghệ và khách bộ hành'}"><div><h1>${title}</h1><p>${description}</p><span>${badge}</span></div></div>`;
export function bazaarView({s,tab,world,online,esc,button}){
 const back=`<div class="rail-return">${button('← Trở lại '+(tab==='bazaar'?'Trung tâm TP. Neon':'Chợ Neon'),'nav',tab==='bazaar'?'hub':'bazaar')}</div>`;
 if(tab==='bazaar')return back+cityBanner('Chợ Neon','Phố chợ công nghệ giữa thành phố. Các gian hàng, môi giới và bạn đồng hành đang chờ bạn.','Thị trường người chơi')+`<div class="section-label">CÓ THỂ TƯƠNG TÁC</div><div class="bazaar-actions">${[['black','weapon','Chợ đen'],['alley','alley','Hẻm thông tin'],['pets','pet','Thiên đường Neon Paws'],['tavern','pub','Quán nhậu Partyline']].map(([id,icon,label])=>`<button data-action="nav" data-id="${id}" class="${id==='tavern'?'highlight':''}">${cityIcon(icon)}<span>${label}</span></button>`).join('')}</div><div class="city-travel-list bazaar-travel">${[['browse','bag','Thăm thị trường người chơi','Mua trang bị từ những runner khác. Giá và module được hiển thị trước khi mua.'],['mine','stall','Gian hàng của tôi','Rao bán trang bị, kiểm tra các tin của bạn và thu hồi món chưa bán.']].map(([id,icon,name,text])=>`<button class="city-travel" data-action="market-section" data-id="${id}"><span class="travel-icon">${cityIcon(icon)}</span><div><b>${name.toUpperCase()}</b><p>${text}</p><small>${id==='mine'?(online?`${world?.market.filter(m=>m.seller===online.id).length||0}/10 tin của bạn`:'Cần đăng nhập'):'Thị trường người chơi'}</small></div></button>`).join('')}</div><div class="section-label">HÀNH ĐỘNG</div><div class="actions">${button('Bồi dưỡng nghề','nav','commercial')}${button('Trở lại trung tâm','nav','hub')}</div>`;
 if(tab==='pets')return back+cityBanner('Thiên Đường Neon Paws','Drone, mèo máy và những sinh vật ánh sáng tìm một runner để cùng đi qua thành phố.','Bạn đồng hành')+`<div class="section-label">THÚ CƯNG <span>${s.pets?.length||0}/${pets.length}</span></div><div class="pet-list district-pets">${pets.map(v=>{const own=s.pets?.includes(v.id);return `<article class="pet-card"><span class="pet-icon">${v.icon}</span><div><b>${esc(v.name)}</b><small>Cấp ${v.level} · ${v.price.toLocaleString('vi')} ₡</small><small>${own?'ĐÃ SỞ HỮU':'Chưa sở hữu'} · Bạn đồng hành trang trí</small></div>${own?button(s.pet===v.id?'Đang đi cùng':'Chọn','pet-select',v.id,s.pet===v.id||!!s.combat||!!s.dungeon):button('Nhận nuôi','pet-buy',v.id,s.level<v.level||s.credits<v.price||!!s.combat||!!s.dungeon)}</article>`;}).join('')}</div>${s.pet?button('Cho thú cưng nghỉ','pet-select','',!!s.combat||!!s.dungeon):''}<p class="hint">Mua một lần bằng credits trong game. Thú cưng không tăng chỉ số chiến đấu. Chỉnh quyền riêng tư trong Hồ sơ → Tài sản.</p>${button('Xem tài sản của tôi','open-assets')}`;
 if(tab==='alley')return back+cityBanner('Hẻm Thông Tin','Tín hiệu rò rỉ và những người không để lại tên. Một manh mối có thể đưa bạn tới hợp đồng tiếp theo.','Khám phá')+`<div class="section-label">HÀNH ĐỘNG</div><article class="alley-contact"><b>NGƯỜI GIỮ SÓNG</b><p>“Nhìn vào hồ sơ khu vực của bạn. Những điều bị xóa vẫn để lại dấu vết.”</p>${button('Nghe tin khu vực','alley-rumor','',!!s.combat||!!s.dungeon)}</article><article class="alley-contact"><b>LỤC TÌM PHẾ LIỆU</b><p>Địa điểm: ${esc(maps.find(m=>m.id===s.map).name)}. Tốn 2 EN, nhận 1 Hash và 1 linh kiện. Mỗi khu vực chỉ tìm một lần.</p>${button(s.scavenged?.includes(s.map)?'Đã tìm ở khu vực này':'Lục tìm · 2 EN','scavenge','',!!s.work||!!s.combat||!!s.dungeon||s.energy<2||s.scavenged?.includes(s.map))}</article><div class="actions">${button('Hợp đồng khu vực','nav','missions')}${button('Gặp cư dân','nav','npc')}</div>`;
 if(tab==='tavern')return back+cityBanner('Quán Nhậu Partyline','Nơi runner gặp nhau, góp quỹ cộng đồng và chia sẻ tin tức sau mỗi chuyến đi.','Cộng đồng')+`<div class="actions">${button('Vào trò chuyện toàn cầu','open-global-chat')}${button('Tìm tập đoàn','nav','corporation')}</div><p class="hint">Quỹ dùng credits trong game, bắt đầu lại mỗi ngày Việt Nam. Khi đủ quỹ, tài khoản online được giảm giá shop theo giờ hiển thị.</p>${communityView({world,s,online,esc,button})}`;
 if(tab==='coast'){const target=maps[1];return `<div class="rail-return">${button('← Trở lại Trung tâm TP. Neon','nav','hub')}</div>`+cityBanner('Bờ Biển Neon','Đèn dẫn đường chạy dọc mặt nước. Ngoài xa, drone vận tải nối cảng với những vùng đất mới.','Bờ biển','coast')+`<div class="section-label">DU HÀNH</div><button class="city-travel" data-action="move" data-id="${target.id}" ${s.map===target.id||s.work||s.combat||s.dungeon||s.energy<1?'disabled':''}><span class="travel-icon">${cityIcon('coast')}</span><div><b>${s.map===target.id?'ĐANG Ở CẢNG TRO':'ĐẾN CẢNG TRO · 1 EN'}</b><p>${esc(target.description)}</p><small>Cấp ${target.level}</small></div></button><div class="actions">${button('Khám phá khu vực hiện tại','nav','terminal')}${button('Bản đồ vùng','nav','map')}</div>`;}
 return '';
}
