import {stats} from './game.js';
import {enemyVariants,enemyProfile,playerMark} from './gear-rules.js';
import {enemies} from './content.js';
import {stacks} from './inventory-state.js';
import {settings} from './settings.js';

export function combatView({s,online,esc,button}) {
 const f=s.combat;if(!f)return '';
 const st=stats(s),bag=stacks(s),hit=s.lastHit;
 const shield=(value,max,name)=>max>0?`<div class="combat-shield"><label><span>${name}</span><b>${Math.max(0,value||0)} / ${max}</b></label><div class="bar shield"><i style="width:${Math.max(0,(value||0)/max*100)}%"></i></div></div>`:'';
 return `<section class="combat" aria-label="Chiến đấu"><div class="combat-heading"><div class="eyebrow">${f.pvp?(online?'PVP BẤT ĐỒNG BỘ':'ĐỐI THỦ MÔ PHỎNG'):'GIAO TRANH'}</div><span>LƯỢT ${f.turn+1}</span></div><h2>${esc(f.name)}</h2><div class="combat-stats"><span>LV <b>${f.level}</b></span><span>ATK <b>${f.attack}</b></span><span>DEF <b>${f.defense}</b></span>${f.faction?`<span>${esc(f.faction)}</span>`:''}</div><div class="combat-hp"><label><span>HP ĐỊCH</span><b>${Math.max(0,f.currentHp)} / ${f.hp}</b></label><div class="bar danger"><i style="width:${Math.max(0,f.currentHp/f.hp*100)}%"></i></div></div><div class="combat-shields">${shield(f.currentShield,f.shield,'Khiên địch')}${shield(s.shield,st.maxShield,'Khiên của bạn')}</div>${!settings(s).hideDamageMeter&&hit?.name===f.name?`<div class="attack-meter"><span>ĐÒN VỪA ĐÁNH <b>${hit.damage}${hit.critical?' · CHÍ MẠNG':''}</b></span><small>${hit.healthDamage??hit.damage} HP · ${hit.shieldDamage||0} khiên</small><div class="bar"><i style="width:${Math.min(100,hit.damage/f.hp*100)}%"></i></div></div>`:''}${s.dungeon?.instance?`<p class="reward">Đóng góp ${f.contribution||0}% / cần 20%${s.level>f.level+12?' · vượt giới hạn cấp nhận thưởng':''}</p>`:''}<div class="combat-weapons"><div><span>CHÍNH · MIỄN PHÍ</span>${button('Tấn công','attack')}<small>${st.attack} ATK</small></div><div><span>ĐẶC BIỆT · ${bag['energy-cell']||0} PIN</span>${button('Phá khiên 120%','special','',!s.equipped.special||!(bag['energy-cell']>0))}<small>${st.specialAttack} ATK</small></div><div><span>HỦY DIỆT · ${bag.antimatter||0} ĐẠN</span>${button('Phá khiên 50%','destructive','',!s.equipped.destructive||!(bag.antimatter>0))}<small>${st.destructiveAttack} ATK</small></div></div><div class="actions combat-utilities">${button('Xung · 3 EN','skill','',s.energy<3)}${button('Thuốc · 25 ₡','heal','',s.credits<25)}${button('Rút lui','escape')}</div><details class="combat-help" data-ui-panel="combat-help"><summary>Chi tiết chiến đấu</summary><p class="hint">Vũ khí đặc biệt và hủy diệt dùng một viên mỗi phát; mua hoặc chế tạo ở Túi đồ. ${st.stun?`Choáng ${Math.round(st.stun*100)}% · `:''}${st.regen?`Tái sinh ${st.regen} HP/lượt · `:''}${s.dungeon?.mode&&s.dungeon.mode!=='normal'?`Rút lui: ${Math.round(st.escape*100)}% thành công.`:'Rút lui luôn thành công ở chế độ hiện tại.'}</p></details></section>`;
}
export function nearbyView({s,esc,button}){
 const source=enemies.find(e=>e.map===s.map),mark=playerMark(s);
 return `<div class="section-label">ĐỊCH GẦN ĐÂY <span>${mark?mark.name:'KHÔNG CÓ DẤU CHỦ ĐẠO'}</span></div><p class="hint">Dấu trên bộ trang bị được chọn theo đa số: Xuyên thấu khắc Helix, Phân rã khắc Bóng Mờ, Chết chóc khắc Liên Minh Tro (+10% sát thương). Khi bằng nhau không có dấu chủ đạo.</p><div class="nearby-enemies">${enemyVariants.map(v=>{const f=enemyProfile(source,v.id);return `<article class="card"><h3>${esc(f.name)}</h3><p>${esc(f.faction)} · ${f.hp} HP / ${f.shield} khiên · ${f.attack} ATK</p><p>${v.description}</p><p class="reward">+${f.xp} XP / +${f.credits} ₡</p>${button('Giao tranh · 2 EN','fight',v.id,!!s.work||!!s.combat||!!s.dungeon||s.energy<2)}</article>`;}).join('')}</div>`;
}
