import {stats} from './game.js';
import {enemyVariants,enemyProfile,playerMark} from './gear-rules.js';
import {enemies} from './content.js';
import {stacks} from './inventory-state.js';
import {settings} from './settings.js';

export function combatView({s,online,esc,button}){
 const f=s.combat;if(!f)return '';const st=stats(s),bag=stacks(s),hit=s.lastHit;
 const shieldBar=(value,max,name)=>max>0?`<p>${name}: ${Math.max(0,value||0)} / ${max}</p><div class="bar shield"><i style="width:${Math.max(0,(value||0)/max*100)}%"></i></div>`:'';
 return `<section class="combat"><div class="eyebrow">${f.pvp?(online?'PVP BẤT ĐỒNG BỘ':'ĐỐI THỦ MÔ PHỎNG'):'GIAO TRANH'} / LƯỢT ${f.turn+1}</div><h2>${esc(f.name)}</h2><p>Cấp ${f.level} · ATK ${f.attack} · DEF ${f.defense}${f.faction?' · '+esc(f.faction):''}</p><div class="bar danger"><i style="width:${Math.max(0,f.currentHp/f.hp*100)}%"></i></div><p>${Math.max(0,f.currentHp)} / ${f.hp} HP</p>${shieldBar(f.currentShield,f.shield,'Khiên địch')}${shieldBar(s.shield,st.maxShield,'Khiên của bạn')}${!settings(s).hideDamageMeter&&hit?.name===f.name?`<div class="attack-meter"><span>ĐÒN VỪA ĐÁNH · ${hit.damage}${hit.critical?' CHÍ MẠNG':''}</span><p>${hit.healthDamage??hit.damage} HP / ${hit.shieldDamage||0} khiên</p><div class="bar"><i style="width:${Math.min(100,hit.damage/f.hp*100)}%"></i></div></div>`:''}${s.dungeon?.instance?`<p class="reward">Đóng góp vào địch này: ${f.contribution||0}% / cần 20%${s.level>f.level+12?' · vượt giới hạn cấp nhận thưởng':''}</p>`:''}<div class="combat-weapons"><div><span>CHÍNH / KHÔNG DÙNG ĐẠN</span>${button('Tấn công · '+st.attack+' ATK','attack')}</div><div><span>ĐẶC BIỆT / PIN ×${bag['energy-cell']||0}</span>${button('Phá khiên 120% · '+st.specialAttack+' ATK','special','',!s.equipped.special||!(bag['energy-cell']>0))}</div><div><span>HỦY DIỆT / ĐẠN ×${bag.antimatter||0}</span>${button('Phá khiên 50% · '+st.destructiveAttack+' ATK','destructive','',!s.equipped.destructive||!(bag.antimatter>0))}</div></div><div class="actions">${button('Xung điện · 3 EN','skill','',s.energy<3)}${button('Thuốc · 25 ₡','heal','',s.credits<25)}${button('Rút lui','escape')}</div><p class="hint">Vũ khí đặc biệt và hủy diệt tiêu hao một viên mỗi phát; mua hoặc chế tạo ở Túi đồ. ${st.stun?`Choáng ${Math.round(st.stun*100)}% · `:''}${st.regen?`Tái sinh ${st.regen} HP/lượt · `:''}${s.dungeon?.mode&&s.dungeon.mode!=='normal'?`Rút lui: ${Math.round(st.escape*100)}% thành công.`:'Rút lui luôn thành công ở chế độ hiện tại.'}</p></section>`;
}
export function nearbyView({s,esc,button}){
 const source=enemies.find(e=>e.map===s.map),mark=playerMark(s);
 return `<div class="section-label">ĐỊCH GẦN ĐÂY <span>${mark?mark.name:'KHÔNG CÓ DẤU CHỦ ĐẠO'}</span></div><p class="hint">Dấu trên bộ trang bị được chọn theo đa số: Xuyên thấu khắc Helix, Phân rã khắc Bóng Mờ, Chết chóc khắc Liên Minh Tro (+10% sát thương). Khi bằng nhau không có dấu chủ đạo.</p><div class="nearby-enemies">${enemyVariants.map(v=>{const f=enemyProfile(source,v.id);return `<article class="card"><h3>${esc(f.name)}</h3><p>${esc(f.faction)} · ${f.hp} HP / ${f.shield} khiên · ${f.attack} ATK</p><p>${v.description}</p><p class="reward">+${f.xp} XP / +${f.credits} ₡</p>${button('Giao tranh · 2 EN','fight',v.id,!!s.work||!!s.combat||!!s.dungeon||s.energy<2)}</article>`;}).join('')}</div>`;
}
