import {settings} from './settings.js';
import {afkEventsView} from './afk-view.js';
import {gear} from './content.js';
const clock=t=>new Date(t).toLocaleString('vi',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
export function chatFeed(world,esc,mode='global',options={}){
 const list=mode==='guild'?world?.guildMessages:world?.messages;
 const entries=(list||[]).map(m=>({time:m.time,html:`<article class="message-card skin-${!options.disableChatEffects&&['cyan','pink','gold'].includes(m.chatSkin)?m.chatSkin:'default'}"><div class="message-name"><b title="${esc(m.name)}">${esc(m.name)}</b>${m.corporationName?`<span title="${esc(m.corporationName)}">[${esc(m.corporationName.replace(/[^\p{L}\p{N}]/gu,'').slice(0,3).toUpperCase())}]</span>`:''}</div><div class="message-content">${m.reply?`<blockquote>↳ ${esc(m.reply.name)}<br>${esc(m.reply.text)}</blockquote>`:''}${m.text?`<p>${esc(m.text)}</p>`:''}${m.item?`<div class="shared-equipment">▣ ${esc(m.item.name)} +${m.item.calibration.level}<small>LV ${m.item.level} · ${m.item.calibration.modules.map(esc).join(' / ')||'Chưa có module'}</small></div>`:''}<button data-action="reply" data-id="${m.id}" aria-label="Trả lời ${esc(m.name)}">↳</button></div><div class="message-meta"><span>LEVEL ${m.level}</span><time>${clock(m.time)}</time></div></article>`}));
 if(mode==='global')for(const event of world?.afk?.events||[])entries.push({time:event.time,html:afkEventsView({afk:{events:[event]}},esc)});
 return entries.length?entries.sort((a,b)=>a.time-b.time).map(v=>v.html).join(''):'<p class="hint">Chưa có tin nhắn trong kênh này.</p>';
}
export function mailFeed(world,online,esc,button){const list=world?.mail||[];return list.length?[...list].reverse().map(m=>{const incoming=m.recipient===online?.id;return `<article class="mail-card ${incoming&&!m.read?'unread':''}"><div><b>${incoming?'TỪ '+esc(m.senderName):'ĐẾN '+esc(m.recipientName)}</b><time>${clock(m.time)}</time></div><p>${esc(m.text)}</p><small>${incoming?m.read?'Đã đọc':'Chưa đọc':'Đã gửi'}</small>${incoming&&!m.read?button('Đánh dấu đã đọc','mail-read',m.id):''}</article>`;}).join(''):'<p class="hint">Chưa có thư.</p>';}
export function notificationsFeed(s,esc){return s.notifications?.length?s.notifications.map(n=>`<article class="mail-card ${n.read?'':'unread'}"><time>${clock(n.time)}</time><p>${esc(n.text)}</p><small>${n.read?'Đã đọc':'Chưa đọc'}</small></article>`).join(''):'<p class="hint">Chưa có thông báo mới. Thông báo được ghi từ các hoạt động kể từ phiên bản này.</p>';}
export function commsView({s,world,online,mode='global',replyId=null,attached=false,esc,button}){
 const messages=mode==='guild'?world?.guildMessages:world?.messages,reply=messages?.find(m=>m.id===replyId),guild=world?.corporations.find(c=>c.id===world.corporation),unreadMail=world?.mail.filter(m=>m.recipient===online?.id&&!m.read).length||0,unreadNotes=s.notifications?.filter(n=>!n.read).length||0;
 const tabs=`<div class="comms-tabs">${[['global','Chat'],['guild','Tập đoàn'],['mail','Thư'],['notifications','Thông báo']].map(([id,label])=>`<button data-action="chat-tab" data-id="${id}" class="${mode===id?'selected':''}">${label}${id==='mail'&&unreadMail||id==='notifications'&&unreadNotes?'<i></i>':''}</button>`).join('')}</div>`;
 const login=!online?`<p class="hint">Đăng nhập để gửi chat, thư và tặng uy tín.</p>${button('Đăng nhập / đăng ký','nav','account')}`:'';
 if(mode==='notifications')return `<section class="comms-screen">${tabs}<div class="section-label">THÔNG BÁO CỦA NHÂN VẬT <span>${unreadNotes} CHƯA ĐỌC</span></div>${button('Đánh dấu tất cả đã đọc','notifications-read','',!unreadNotes)}<div class="notifications-list">${notificationsFeed(s,esc)}</div></section>`;
 if(mode==='mail')return `<section class="comms-screen">${tabs}<div class="section-label">THƯ RIÊNG <span>${unreadMail} CHƯA ĐỌC</span></div><p class="hint">Chỉ người gửi và người nhận được đọc thư. Tối đa 1.000 ký tự; mỗi thư cách nhau ít nhất 5 giây.</p><div class="mail-list">${mailFeed(world,online,esc,button)}</div><form class="world-form mail-compose" data-kind="mail-send"><label>Gửi đến<select name="id" aria-label="Người nhận thư" required ${!online?'disabled':''}>${world?.players.filter(p=>p.id!==online?.id).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><textarea name="text" id="mail-text" maxlength="1000" rows="4" placeholder="Nội dung thư…" aria-label="Nội dung thư" required ${!online?'disabled':''}></textarea><button ${!online||!world?.players.some(p=>p.id!==online.id)?'disabled':''}>Gửi thư</button></form>${login}</section>`;
 const enabled=!!online&&(mode!=='guild'||!!guild),fund=f=>world?.funds.find(v=>v.id===f)?.active||false;
 return `<section class="comms-screen chat-mode">${tabs}<div class="chat-channel-bar"><select id="chat-channel" aria-label="Kênh trò chuyện"><option value="global" ${mode==='global'?'selected':''}>GLOBAL</option><option value="guild" ${mode==='guild'?'selected':''}>TẬP ĐOÀN</option></select><div class="chat-buffs"><span class="yellow" title="Giảm thời gian AFK toàn server">◷ ${world?.afk?.speed||0}%</span><span class="blue">⚒ ${fund('morning')?'2':'0'}%</span><span class="cyan">⚒ ${fund('evening')?'3':'0'}%</span><span class="yellow">♢ ${fund('global')?'5':'0'}%</span></div>${button('♙','nav','reputation')}${button('◌','nav','cosmetics')}</div>${mode==='guild'?`<p class="hint">${guild?'Kênh riêng: '+esc(guild.name):'Gia nhập tập đoàn để đọc và gửi tin trong kênh riêng.'}</p>${!guild?button('Tìm tập đoàn','nav','corporation'):''}`:''}<div class="chat-feed" aria-live="polite">${world?chatFeed(world,esc,mode,settings(s)):'<p class="hint">Chưa tải được trò chuyện.</p>'}</div>${reply?`<div class="reply-preview"><span>↳ Trả lời ${esc(reply.name)}: ${esc(reply.text.slice(0,100))}</span>${button('×','reply-cancel')}</div>`:''}<form class="world-form chat-compose" data-kind="chat"><div class="chat-input-wrap"><button type="button" data-action="attach-item" aria-label="Chia sẻ trang bị" ${!enabled?'disabled':''}>♧</button><textarea id="chat-text" name="text" maxlength="256" rows="2" placeholder="Nhập tin nhắn…" aria-label="Tin nhắn" ${!enabled?'disabled':''}></textarea><small id="chat-count">0 / 256</small></div>${attached?`<select id="chat-item" name="item" aria-label="Trang bị chia sẻ"><option value="">Không đính kèm</option>${gear.filter(g=>s.inventory.includes(g.id)).map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select>`:''}<button class="chat-send" ${!enabled?'disabled':''}>GỬI</button></form><p class="chat-rule">256 ký tự · Cách nhau 2 giây · Cập nhật mỗi 5 giây</p>${login}</section>`;
}
export function reputationView({world,online,esc,button}){return `<div class="section-label">TẶNG DANH TIẾNG / UY TÍN</div><p class="hint">Tặng runner khác 1 uy tín để bày tỏ sự kính trọng hoặc lòng biết ơn. Mỗi tài khoản được tặng một lần mỗi ngày Việt Nam. Không thể tự tặng.</p>${!online?button('Đăng nhập','nav','account'):''}<div class="reputation-list">${world?.players.map(p=>`<article><div><b>${esc(p.name)}</b><small>Cấp ${p.level} · Uy tín ${p.reputation}</small></div>${button('Tài sản','public-profile',p.id)}${button(p.id===online?.id?'Bạn':world.commendedToday.length?'Đã tặng hôm nay':'Tặng +1','rep-give',p.id,!online||p.id===online.id||!!world.commendedToday.length)}</article>`).join('')||'<p class="hint">Chưa có tài khoản tham gia.</p>'}</div>`;}
