const districts=['Hẻm Neon','Cảng Tro','Tháp Kính','Chợ Dưới','Ga Bỏ Hoang','Vườn Silicon','Hầm Tín Hiệu','Vành Đai Đỏ'];
const factions=['Bóng Mờ','Helix','Người Nhặt Sóng','Liên Minh Tro','Kẻ Không Tên'];
export const maps=Array.from({length:40},(_,i)=>({id:`map${i}`,name:`${districts[i%8]} / ${['Ngoại vi','Tầng ngầm','Trung tâm','Vùng cấm','Lõi mạng'][Math.floor(i/8)]}`,level:1+i,description:`${['Mưa axit gõ lên mái tôn. Một drone tuần tra quét ánh đỏ qua những sạp hàng.','Các đường dây điện đứt lóe sáng giữa đống container. Tín hiệu cầu cứu vẫn lặp lại.','Hologram quảng cáo che kín cửa sổ. Phía sau lớp kính là những thí nghiệm bị bỏ lại.','Tiếng rao hàng bị nhiễu trộn vào tiếng máy phát. Mọi giao dịch đều có một cái giá.','Chuyến tàu cuối không bao giờ đến. Có thứ gì đó vẫn di chuyển dưới đường ray.','Rễ cây nhân tạo len vào mạch điện. Không khí ngọt một cách đáng ngờ.','Một giọng nói đọc tên bạn qua bộ đàm. Nó chưa từng được cấp quyền truy cập.','Bức tường cách ly rung lên sau mỗi đợt xung điện. Bên kia không còn luật lệ.'][i%8]}`,faction:factions[i%5]}));
const weapons=['Súng xung','Dao plasma','Carbine','Búa từ','Súng rail','Kiếm điện','SMG','Nỏ ion','Rifle nhiệt','Găng chấn động'];
const armor=['Áo giáp','Mũ phản quang','Lớp da tổng hợp','Giáp sợi','Khiên nano','Mặt nạ','Áo khoác chiến thuật','Bộ chống nhiễu','Giáp gốm','Vỏ titan'];
const mods=['Chip phản xạ','Lõi quang học','Bộ tăng lực','Mạch chiến đấu','Ống dẫn ion','Bộ giải mã','Chip hồi phục','Pin lượng tử','Mắt nhân tạo','Bộ ổn định'];
export const gear=Array.from({length:200},(_,i)=>{const tier=Math.floor(i/40),slot=['weapon','armor','implant'][i%3];return{id:`gear${i}`,name:`${(slot==='weapon'?weapons:slot==='armor'?armor:mods)[i%10]} ${['Tro','Neon','Helix','Ma','Zero'][tier]}-${String(i%40+1).padStart(2,'0')}`,slot,rarity:tier,level:1+tier*8+Math.floor(i%40/5),power:3+tier*12+i%8,price:40+tier*180+(i%40)*12,black:tier>=3,description:`Thiết bị ${slot==='weapon'?'tấn công':slot==='armor'?'phòng thủ':'cấy ghép'} do ${factions[i%5]} lắp ráp. ${['Ổn định và dễ sửa chữa.','Được gia cố cho các cuộc đột kích.','Tích hợp công nghệ quân sự.','Số sê-ri đã bị xóa.','Nguyên mẫu thất lạc từ lõi mạng.'][tier]}`};});
export const npcs=Array.from({length:80},(_,i)=>({id:`npc${i}`,name:`${['Mika','Vex','An','Rook','Yuna','Kha','Echo','Linh','Sable','Duy'][i%10]} ${['Thợ Máy','Chạy Tin','Giữ Cửa','Bác Sĩ','Môi Giới','Lưu Trữ','Dẫn Đường','Ẩn Danh'][Math.floor(i/10)]}`,map:`map${i%40}`,faction:factions[i%5],dialogue:`${['Nếu nghe tiếng bước chân sau lưng, đừng quay lại. Hãy tìm một nguồn sáng.','Helix mua ký ức của chúng ta rồi bán lại dưới tên mới.','Tôi từng có một người em. Giờ chỉ còn tín hiệu của nó trên mạng.','Đừng tin những drone sơn trắng. Chúng không phải cứu hộ.','Giữ lại linh kiện. Ở đây, một con ốc còn giá trị hơn lời hứa.','Dưới ga tàu có một lối thoát. Nhưng cần ai đó đánh thức bộ điều khiển.','Tôi sửa máy, không sửa lương tâm. Muốn giúp thì dọn bọn lính ngoài kia.','Thành phố không ngủ. Nó chỉ giả vờ không nhìn thấy chúng ta.'][Math.floor(i/10)]} Mật mã hôm nay là ${districts[i%8]}.`}));
export const enemies=Array.from({length:40},(_,i)=>({id:`enemy${i}`,name:`${['Drone truy sát','Lính Helix','Kẻ cấy ghép','Thợ săn dữ liệu','Bóng nhiễu','Robot phế liệu','Đặc vụ vô danh','Chó máy'][i%8]} / ${i+1}`,map:`map${i}`,level:i+1,hp:24+i*9,attack:4+i*2,defense:Math.floor(i/3),xp:12+i*5,credits:15+i*7}));
export const bosses=Array.from({length:40},(_,i)=>({id:`boss${i}`,name:`${['Bà Chúa Rỉ Sét','Giám Đốc Rỗng','Mắt Thứ Ba','Người Gác Tàu','Thánh Máy','Tiếng Vọng','Mẹ Drone','ZERO-NULL'][i%8]} / ${i+1}`,map:`map${i}`,level:i+1,hp:85+i*18,attack:8+i*3,defense:2+Math.floor(i/2),xp:60+i*15,credits:100+i*25,boss:true,description:`Thực thể kiểm soát ${maps[i].name}. Mỗi đòn thứ ba gây sát thương xung điện tăng gấp đôi.`}));
export const quests=Array.from({length:100},(_,i)=>({id:`quest${i}`,name:`${['Dọn đường','Thu hồi tín hiệu','Món nợ máu','Đường dây đứt','Ký ức cuối'][i%5]}: ${maps[i%40].name}`,map:`map${i%40}`,npc:`npc${i%80}`,level:maps[i%40].level,target:i%5===4?'boss':'enemy',count:i%5===4?1:2+i%3,xp:40+i*5,credits:70+i*12,story:`${npcs[i%80].name} cần bạn ${i%5===4?'hạ kẻ đang kiểm soát khu vực':'loại bỏ lực lượng thù địch để lấy lại bộ dữ liệu'}. Hồ sơ đó chứa bằng chứng về ${['buôn bán ký ức','thử nghiệm người máy','mất tích dân thường','đánh cắp năng lượng','dự án tái tạo ý thức'][i%5]}.`}));
export const content={maps,gear,npcs,enemies,bosses,quests};
export const rarities=['Phổ thông','Cải tiến','Hiếm','Sử thi','Huyền thoại','Di sản'];
// Expansion appends records; the original 500 IDs and their contents stay intact.
const summit=['Cổng Kính Đen','Chợ Quỹ Đạo','Bến Năng Lượng','Hành Lang Trắng','Vườn Trọng Lực','Xưởng Mạch Sống','Hố Dữ Liệu','Cầu Từ Trường','Tháp Ánh Sáng','Lõi Thiên Đỉnh'];
for(let i=0;i<10;i++){
 const level=41+i,map=`map${40+i}`,npc=`npc${80+i}`;
 maps.push({id:map,name:summit[i]+' / Thiên Đỉnh',level,faction:factions[i%5],description:`${summit[i]} nằm trên mạng đường ray treo của Thiên Đỉnh. Dữ liệu của cư dân bị khóa trong những lõi quang học; lực lượng ${factions[i%5]} đang tranh giành quyền kiểm soát.`});
 npcs.push({id:npc,name:['Ari','Nia','Tâm','Kite','Mira','Hạ','Zero','Minh','Nox','Yên'][i]+' / Thiên Đỉnh',map,faction:factions[i%5],dialogue:`Đường lên ${summit[i]} không còn an toàn. Hãy thu hồi các lõi bị đánh cắp trước khi máy chủ xóa ký ức của chúng tôi.`});
 enemies.push({id:`enemy${40+i}`,name:['Drone quang tử','Lính phản trọng lực','Thợ săn lõi','Bóng dữ liệu','Robot gác cổng'][i%5]+' / '+level,map,level,hp:410+i*14,attack:78+i*3,defense:18+i,xp:230+i*10,credits:350+i*15});
 bosses.push({id:`boss${40+i}`,name:['Người Gác Thiên Đỉnh','Mắt Quỹ Đạo','Kiến Trúc Sư Rỗng','Hạt Nhân Trắng','Bóng Cuối'][i%5]+' / '+level,map,level,hp:900+i*35,attack:110+i*5,defense:24+i,xp:650+i*30,credits:1500+i*90,boss:true,description:`Thực thể khóa dữ liệu ở ${summit[i]}. Mỗi đòn thứ ba gây xung điện tăng gấp đôi.`});
 quests.push({id:`quest${100+i}`,name:'Ký ức Thiên Đỉnh: '+summit[i],map,npc,level,target:i%5===4?'boss':'enemy',count:i%5===4?1:3,xp:400+i*20,credits:800+i*50,story:`Cư dân ${summit[i]} cần bạn giành lại bộ lõi chứa ký ức của họ từ lực lượng chiếm đóng.`});
 for(let j=0;j<3;j++)gear.push({id:`gear${200+i*3+j}`,name:['Carbine quang tử','Giáp phản trọng lực','Lõi đồng bộ'][j]+' Thiên Đỉnh-'+String(i+1).padStart(2,'0'),slot:['weapon','armor','implant'][j],rarity:5,level,power:75+i*3+j,price:2000+i*160+j*80,black:true,description:`Nguyên mẫu Di sản cấp ${level}, thu hồi từ xưởng quang học Thiên Đỉnh. Các mạch tự ổn định được thiết kế cho môi trường ngoài vành đai.`});
}
export const contentCount=Object.values(content).reduce((n,list)=>n+list.length,0);
