import {expeditionLobby,partyPanel} from './expedition-view.js';
import {dungeonModes,modePlan,dungeonQuestView} from './dungeon-events.js';
import {maps} from './content.js';
import {stats} from './game.js';
import {directions} from './dungeon.js';
export function dungeonView({s,esc,button,combat,online,world}){
 const d=s.dungeon;if(!d)return `<div class="dungeon-lobby"><div class="eyebrow">EXPEDITION / SOLO</div><h1>Hầm tín hiệu</h1><p>Ba tầng dưới ${esc(maps.find(m=>m.id===s.map).name)}. Mỗi tầng có boss giữ cửa, rương và điểm hồi phục. Đi vào kẻ địch để giao tranh; tiến tới cửa △ sau khi hạ boss.</p><div class="dungeon-legend"><span>@ Runner</span><span># Tường</span><span>♟ Địch</span><span>Ω Boss</span><span>▤ Rương</span><span>+ Hồi phục</span><span>! Ký ức</span><span>? Nhiệm vụ</span><span>△ Cửa tầng</span></div><div class="dungeon-mode-list">${dungeonModes.map(m=>`<article class="card"><h3>${m.name}</h3><p>HP địch ×${m.hp} · tấn công ×${m.attack} · thưởng trận ×${m.reward} · ${m.tokens} token khi hoàn thành</p>${m.id==='corporation'?'<p class="hint">Cần tài khoản, thành viên tập đoàn và cấp 10. Đây là thử thách cá nhân dành cho thành viên.</p>':''}${button('Vào '+m.name.toLowerCase()+' · '+m.energy+' EN','enter-dungeon',m.id,!!s.work||!!s.combat||s.energy<m.energy||m.id==='corporation'&&(!online||!world?.corporation||s.level<10))}</article>`).join('')}</div><p class="hint">Chạm ô liền kề hoặc dùng phím mũi tên / WASD. Có nút di chuyển trên điện thoại. Di chuyển không tốn EN; giao tranh tốn 2 EN. Rời dungeon giữ loot và đóng lượt hiện tại.</p><div class="dungeon-record">${s.dungeonClears||0} LƯỢT HOÀN THÀNH / ${s.dungeonRuns||0} LƯỢT ĐÃ VÀO</div>${expeditionLobby({s,world,online,esc,button})}</div>`;
 const teammates=(world?.party||[]).filter(v=>v.floor===d.floor),st=stats(s),glyph={'#':'#','.':'·',E:'▥',X:'△',B:'Ω',M:'♟',C:'▤',H:'+',T:'!',Q:'?'},labels={'#':'Tường','.':'Sàn',E:'Lối vào',X:'Cửa tầng',B:'Boss',M:'Địch',C:'Rương',H:'Trạm cứu trợ',T:'Hồ sơ ký ức',Q:'Người giữ hầm'};
 return `<section class="dungeon-screen"><div class="dungeon-top">${button('‹ Rời dungeon','leave-dungeon','',!!s.combat)}<span>${modePlan(d).name.toUpperCase()} · TẦNG ${d.floor} / 3 · LV ${s.level}</span></div><div class="dungeon-health"><span>HEALTH</span><div><i style="width:${s.hp/st.maxHp*100}%"></i><b>${s.hp} / ${st.maxHp}</b></div></div><div class="dungeon-grid-wrap"><div class="dungeon-map-meta"><span>♟ ${d.cells.filter(c=>c==='M').length} · Ω ${d.bossDefeated?0:1}</span><span>▤ ${d.cells.filter(c=>c==='C').length} · @ ${teammates.length||1} RUNNER</span></div><div class="dungeon-grid" role="group" aria-label="Bản đồ dungeon" style="--columns:${d.width}">${d.cells.map((cell,i)=>{const x=i%d.width,y=Math.floor(i/d.width),player=x===d.x&&y===d.y,ally=teammates.find(v=>v.x===x&&v.y===y&&!player),near=Math.abs(x-d.x)+Math.abs(y-d.y)===1,dir=Object.entries(directions).find(([,v])=>d.x+v[0]===x&&d.y+v[1]===y)?.[0];return `<button class="tile tile-${cell==='#'?'wall':cell==='.'?'floor':cell} ${player?'player-tile':ally?'ally-tile':''} ${d.visited.includes(i)?'visited':''} ${near&&cell!=='#'?'adjacent':''}" data-action="dungeon-step" data-id="${dir||''}" ${!near||cell==='#'||s.combat?'disabled':''} aria-label="${player?'Bạn':ally?esc(ally.name):labels[cell]}, cột ${x+1}, hàng ${y+1}">${player?'@':ally?'◉':glyph[cell]}</button>`;}).join('')}</div><div class="dungeon-player-name">${esc(s.name)} / ${esc(maps.find(m=>m.id===d.map).name)}</div></div><div class="dungeon-status" role="status">${d.bossDefeated?'CỬA ĐÃ MỞ / ĐẾN △ ĐỂ TIẾP TỤC':'TÌM Ω / HẠ BOSS ĐỂ MỞ CỬA TẦNG'}</div>${partyPanel({s,world,esc})}${s.lastLore?.id==='lore-'+d.map?`<article class="card"><h3>! ${esc(s.lastLore.title)}</h3><p>${esc(s.lastLore.text)}</p></article>`:''}${dungeonQuestView(s,button)}${combat()}<div class="dungeon-controls" aria-label="Di chuyển"><span></span>${button('↑','dungeon-step','up',!!s.combat)}<span></span>${button('←','dungeon-step','left',!!s.combat)}<span class="control-center">@</span>${button('→','dungeon-step','right',!!s.combat)}<span></span>${button('↓','dungeon-step','down',!!s.combat)}<span></span></div><div class="dungeon-legend"><span># Tường</span><span>♟ Địch</span><span>Ω Boss</span><span>▤ Rương</span><span>+ Hồi phục</span><span>! Ký ức</span><span>? Nhiệm vụ</span><span>△ Cửa tầng</span></div><p class="dungeon-last-log">${esc(s.log[0])}</p></section>`;
}
