import {maps} from './content.js';
import {dungeonModes,modePlan} from './dungeon-events.js';

export function expeditionLobby({s,world,online,esc,button}){
 if(!online)return `<article class="card"><h3>Dungeon phối hợp</h3><p>Đăng nhập để mở hoặc gia nhập phòng bốn runner. Cùng đánh địch có HP chung; rương và thưởng hoàn thành riêng cho mỗi người.</p>${button('Đăng nhập','auth-open')}</article>`;
 const list=world?.expeditions||[];
 return `<section class="expedition-lobby"><div class="section-label">DUNGEON PHỐI HỢP <span>${list.length} PHÒNG</span></div><p>Runner cùng khu vực có thể gia nhập. Đóng góp ít nhất 20% tổng HP + khiên để nhận thưởng địch; nhân vật cao hơn địch quá 12 cấp không nhận thưởng. Rời hoặc thua sẽ không thể vào lại cùng phòng.</p><form class="world-form expedition-form" data-kind="expedition-create"><label>Tên phòng<input name="text" minlength="3" maxlength="40" required placeholder="Đội săn tín hiệu"></label><label>Độ khó<select name="mode">${dungeonModes.map(v=>`<option value="${v.id}" ${v.id==='corporation'&&(!world?.corporation||s.level<10)?'disabled':''}>${v.name} · ${v.energy} EN</option>`).join('')}</select></label><label>Mật khẩu (tùy chọn)<input name="password" type="password" maxlength="64" autocomplete="new-password" placeholder="Để trống cho mọi người vào"></label><button ${s.combat||s.dungeon||s.work?'disabled':''}>Mở phòng phối hợp</button></form><div class="expedition-list">${list.map(e=>`<article class="card"><h3>${esc(e.name)}</h3><p>${esc(maps.find(m=>m.id===e.map)?.name)} · ${esc(modePlan(e).name)} · ${e.count}/${e.limit} runner</p><p>Chủ phòng: ${esc(e.ownerName)}${e.protected?' · Có mật khẩu':''}</p><form class="world-form expedition-form" data-kind="expedition-join" data-id="${e.id}">${e.protected?'<label>Mật khẩu phòng<input name="password" type="password" maxlength="64" autocomplete="off" required></label>':''}<button ${e.joined||e.departed||e.count>=e.limit||s.map!==e.map||s.combat||s.dungeon||s.work?'disabled':''}>${e.departed?'Đã rời phòng':e.joined?'Đã tham gia':s.map!==e.map?'Đến đúng khu vực trước':'Gia nhập phòng'}</button></form></article>`).join('')||'<p class="hint">Chưa có phòng mở. Tạo phòng để runner khác gia nhập.</p>'}</div><p class="hint">Phòng tập đoàn chỉ hiển thị với thành viên cùng tập đoàn. Phòng hết hạn sau hai giờ không hoạt động. Mật khẩu phòng được băm trên server.</p></section>`;
}
export function partyPanel({s,world,esc}){
 if(!s.dungeon?.instance)return '';
 return `<article class="card party-panel"><h3>Đội phối hợp · HP địch dùng chung</h3><p>Rương là loot riêng. Đồng đội có thể mở cửa bằng cách hạ boss.</p>${(world?.party||[]).map(v=>`<div><b>${esc(v.name)}</b><span>LV ${v.level} · ${v.hp} HP · Tầng ${v.floor} (${v.x},${v.y})</span></div>`).join('')}</article>`;
}
