import {areaAccess} from './rail.js';
import {bagSize,capacity,ownsGear,receiveGear,receiveStack,blueprintDrop} from './inventory-state.js';
import {record,activity} from './journal.js';
import {pveKills} from './achievements.js';
import {gear,maps,enemies,bosses,quests} from './content.js';
import {itemStats} from './equipment.js';
import {resolveDungeonCombat} from './dungeon-layout.js';
export function fresh(){return{version:1,railVersion:1,keyFragments:{},railKeys:[],createdAt:new Date().toISOString(),name:'Runner',level:1,xp:0,credits:180,units:3,scrap:6,bank:0,hp:100,energy:30,map:'map0',inventory:['gear0','gear1'],equipped:{weapon:'gear0',armor:'gear1',implant:null},active:[],completed:[],progress:{},wins:0,losses:0,kills:0,combat:null,log:['Kết nối thành công. Chào mừng đến thành phố tro.']};}
export function stats(s){const weapon=itemStats(s,s.equipped.weapon),armor=itemStats(s,s.equipped.armor),implant=itemStats(s,s.equipped.implant);const fitted=[weapon,armor,implant],sum=k=>fitted.reduce((total,g)=>total+g[k],0);return{maxHp:90+s.level*10+sum('health'),attack:8+s.level*2+weapon.power+Math.floor(implant.power/2)+sum('damage'),defense:2+s.level+armor.power+sum('armor'),crit:Math.min(0.5,0.15+sum('crit')),maxEnergy:30};}
export function note(s,t){record(s,t);}
export function gain(s,xp){s.xp+=xp;while(s.xp>=s.level*60){s.xp-=s.level*60;s.level++;s.hp=stats(s).maxHp;s.energy=30;note(s,`Lên cấp ${s.level}! Sinh lực và năng lượng hồi đầy.`);}}
export function move(s,id){const m=maps.find(m=>m.id===id);if(s.work||s.dungeon||s.combat||!m||!areaAccess(s,m)||m.level>s.level+2||s.energy<1)return false;s.map=id;s.energy--;note(s,`Đã đến ${m.name}.`);return true;}
export function startFight(s,type='enemy',inDungeon=false){if(s.dungeon&&!inDungeon)return false;if(s.work||s.combat||s.hp<=0||s.energy<2)return false;const foe=(type==='boss'?bosses:enemies).find(e=>e.map===s.map);s.energy-=2;s.lastHit=null;s.combat={...foe,currentHp:foe.hp,turn:0,pvp:false};note(s,`Chạm trán ${foe.name}.`);return true;}
export function pvp(s){if(s.work||s.dungeon||s.combat||s.hp<=0||s.energy<3)return false;s.energy-=3;s.lastHit=null;const lv=Math.max(1,s.level+(s.wins%3)-1);s.combat={id:'arena',name:['Ghost','Raven','Kite','Circuit'][s.wins%4],level:lv,hp:65+lv*10,currentHp:65+lv*10,attack:6+lv*3,defense:2+lv,xp:20+lv*4,credits:30+lv*10,turn:0,pvp:true};return true;}
export function turn(s,action,random=Math.random){const f=s.combat;if(!f||!['attack','skill','heal','escape','consumable'].includes(action))return false;const st=stats(s);if(action==='escape'){resolveDungeonCombat(s,f,'escape');s.combat=null;note(s,'Bạn rút lui.');return true;}if(action==='heal'){if(s.credits<25)return false;s.credits-=25;s.hp=Math.min(st.maxHp,s.hp+45);activity(s,'heals');note(s,'Tiêm thuốc: +45 HP.');}else if(action!=='consumable'){if(action==='skill'&&s.energy<3)return false;if(action==='skill')s.energy-=3;const crit=random()<st.crit;const damage=Math.max(1,Math.floor(st.attack*(action==='skill'?1.8:1)*(crit?1.5:1))-f.defense);f.currentHp-=damage;s.lastHit={damage,critical:crit,name:f.name,maxHp:f.hp,time:Date.now()};note(s,`${action==='skill'?'Xung điện':'Tấn công'}${crit?' chí mạng':''}: ${damage} sát thương.`);}
if(f.currentHp<=0){resolveDungeonCombat(s,f,'victory');s.credits+=f.credits;gain(s,f.xp);s.kills++;s.lastVictory={id:String(s.kills)+':'+Date.now(),name:f.name,xp:f.xp,credits:f.credits,pvp:f.pvp};if(f.pvp)s.wins++;else{s.scrap=(s.scrap??6)+(f.boss?3:1);const key=`${s.map}:${f.boss?'boss':'enemy'}`;s.progress[key]=(s.progress[key]||0)+1;if(f.boss){receiveStack(s,'balm',3);note(s,'Chiến lợi phẩm: 3 thuốc giảm đau; túi đầy sẽ gửi vào hộp thư.');s.hashProcessors=(s.hashProcessors||0)+1;note(s,'Nhặt được 1 bộ xử lý Hash.');if(s.map==='map19')note(s,'Thu được Chìa khóa bí mật Neon.');}if(pveKills(s)%3===0){blueprintDrop(s,['weapon','armor','implant'][Math.floor(pveKills(s)/3)%3],Math.min(5,Math.floor(Number(s.map.slice(3))/8)));s.aiCores=(s.aiCores||0)+1;note(s,'Nhặt được 1 lõi AI.');}const pool=gear.filter(g=>g.level<=s.level+2);if(random()<0.45&&pool.length){const item=pool[Math.floor(random()*pool.length)];if(receiveGear(s,item.id)){note(s,`${s.itemInbox?.includes(item.id)?'Túi đầy, gửi vào hộp thư:':'Nhặt được'} ${item.name}.`);}}}note(s,`Hạ ${f.name}: +${f.xp} XP, +${f.credits}₡.`);s.combat=null;return true;}
f.turn++;const damage=Math.max(1,f.attack*(f.boss&&f.turn%3===0?2:1)-Math.floor(st.defense/2));s.hp=Math.max(0,s.hp-damage);note(s,`${f.name} gây ${damage} sát thương.`);if(s.hp===0){resolveDungeonCombat(s,f,'defeat');if(f.pvp)s.losses++;s.credits=Math.max(0,s.credits-Math.floor(s.credits*0.1));s.hp=Math.ceil(st.maxHp*0.5);s.combat=null;note(s,'Bạn được cứu về trạm y tế. Mất 10% credits, hồi 50% HP.');}return true;}
export function shopPrice(item,discount=0){return Math.ceil(item.price*(1-Math.max(0,Math.min(.1,discount))));}
export function buy(s,id,black=false,discount=0){const item=gear.find(g=>g.id===id);if(s.combat||!item||bagSize(s)>=capacity||item.black!==black||ownsGear(s,id)||s.credits<shopPrice(item,discount)||item.level>s.level)return false;s.credits-=shopPrice(item,discount);s.inventory.push(id);activity(s,'trades');note(s,`Mua ${item.name}.`);return true;}
export function equip(s,id){const g=gear.find(g=>g.id===id);if(s.combat||!g||!s.inventory.includes(id)||g.level>s.level)return false;s.equipped[g.slot]=id;s.hp=Math.min(s.hp,stats(s).maxHp);return true;}
export function sell(s,id){const g=gear.find(g=>g.id===id);if(s.combat||!g||!s.inventory.includes(id)||Object.values(s.equipped).includes(id))return false;s.inventory=s.inventory.filter(x=>x!==id);if(s.calibration)delete s.calibration[id];s.hp=Math.min(s.hp,stats(s).maxHp);s.credits+=Math.floor(g.price*0.4);activity(s,'trades');return true;}
export function accept(s,id){const q=quests.find(q=>q.id===id);if(!q||q.level>s.level+2||s.active.includes(id)||s.completed.includes(id)||s.active.length>=5)return false;s.active.push(id);s.progress[`start:${id}`]=s.progress[`${q.map}:${q.target}`]||0;return true;}
export function questProgress(s,q){return Math.min(q.count,Math.max(0,(s.progress[`${q.map}:${q.target}`]||0)-(s.progress[`start:${q.id}`]||0)));}
export function claim(s,id){const q=quests.find(q=>q.id===id);if(s.work||s.combat||!q||!s.active.includes(id)||questProgress(s,q)<q.count)return false;s.active=s.active.filter(x=>x!==id);s.completed.push(id);s.credits+=q.credits;gain(s,q.xp);note(s,`Hoàn thành ${q.name}.`);return true;}
export function rest(s){if(s.work||s.dungeon||s.combat)return false;s.hp=stats(s).maxHp;s.energy=30;note(s,'Nghỉ tại trạm an toàn. HP và năng lượng hồi đầy.');return true;}
