import {equipmentSlots,playerMark} from './gear-rules.js';
import {inboxView} from './inbox-view.js';
import {craftingView} from './crafting-view.js';
import {materials,ammunition} from './inventory-state.js';
import {keysView} from './keys-view.js';
import {gear,rarities} from './content.js';
import {hasKey} from './achievements.js';
import {itemStats} from './equipment.js';
import {supplies,blueprints,stacks,bagSize,capacity,bagCapacity} from './inventory-state.js';
import {quickSlots,craftPool} from './inventory.js';
export function inventoryView({s,section,subsection,filter,search,sort,selected,craftCategory,hideUnavailable,inboxPage,esc,button,gearCard,icon,slotName}){
 const bag=stacks(s),equipped=Object.values(s.equipped),q=quickSlots(s),match=v=>v.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'));
 const tabs=`<div class="inventory-tabs">${[['equipped','Đang mặc'],['bag','Túi đồ'],['inbox','Hộp thư'],['craft','Chế tạo']].map(([id,name])=>`<button class="${section===id?'selected':''}" data-action="inventory-tab" data-id="${id}">${name}${id==='inbox'&&(s.itemInbox?.length||Object.keys(s.stackInbox||{}).length||!s.inventoryWelcomeClaimed)?'<i></i>':''}</button>`).join('')}</div>`;
 if(section==='equipped')return tabs+`<div class="section-label">KHE NHANH <span>1 VẬT PHẨM / LƯỢT</span></div><div class="quick-slots">${q.map((id,i)=>{const v=supplies.find(v=>v.id===id);return `<button data-action="item-use" data-id="${id||''}" ${!v||!(bag[id]>0)?'disabled':''}><span>${v?.icon||'+'} ${v?.name||'Khe trống'}</span><small>×${bag[id]||0}</small></button>`;}).join('')}</div><details class="inventory-settings" data-panel="quick"><summary>Chọn vật phẩm dùng nhanh</summary>${[0,1,2].map(i=>`<form class="inventory-form" data-kind="quick-set" data-slot="${i}"><label>Khe ${i+1}<select name="id"><option value="">Trống</option>${supplies.map(v=>`<option value="${v.id}" ${q[i]===v.id?'selected':''}>${v.name} ×${bag[v.id]||0}</option>`).join('')}</select></label><button>Lưu</button></form>`).join('')}</details><div class="section-label">ĐÃ TRANG BỊ <span>${playerMark(s)?.name||'DẤU CÂN BẰNG'} / LV ${s.level}</span></div><div class="loadout">${equipmentSlots.map(slot=>{const g=gear.find(g=>g.id===s.equipped[slot]);return g?gearCard(g):`<button class="empty-slot" data-action="inventory-tab" data-id="bag">${icon(slot)}<span>${slotName(slot)}<small>Chưa lắp / mở túi đồ</small></span><b>＋</b></button>`;}).join('')}</div><details class="inventory-settings" data-panel="loadouts"><summary>▣ Bộ trang bị đã lưu</summary><p class="hint">Lưu hai bộ để đổi nhanh ngoài dungeon và giao tranh. Trang bị đã bán hoặc chuyển đi cần được thay thế trước khi áp dụng.</p>${[0,1].map(i=>`<div class="loadout-preset"><span>BỘ ${i+1}</span>${button('Lưu bộ hiện tại','loadout-save',String(i))}${button('Áp dụng','loadout-apply',String(i),!s.loadouts?.[i])}</div>`).join('')}</details>${s.combat?button('Quay lại giao tranh','nav',s.dungeon?'dungeon':s.combat.pvp?'arena':'terminal'):''}`;
 if(section==='inbox')return tabs+inboxView({s,page:inboxPage,esc,button});
 if(section==='craft')return tabs+craftingView({s,category:craftCategory,hideUnavailable,esc,button});
 const groupTabs=`<div class="inventory-subtabs">${[['items','Vật phẩm'],['keys','Chìa khóa']].map(([id,name])=>button(name,'bag-section',id,subsection===id)).join('')}</div>`;
 if(subsection==='keys')return tabs+groupTabs+`<div class="section-label">CHÌA KHÓA NHIỆM VỤ</div>${hasKey(s)?'<article class="inbox-item"><h3>⚿ Chìa khóa bí mật Neon</h3><p>Thu được từ boss khu vực 20; bằng chứng tiến trình không thể bán.</p></article>':'<p class="hint">Chìa khóa bí mật Neon: hạ boss khu vực 20.</p>'}${keysView(s,esc,button)}${button('Đến ga tàu trung tâm','nav','rail')}`;
 const categories=[['all','≡','Tất cả'],['weapon','⌁','Vũ khí'],['armor','▣','Giáp'],['implant','⬡','Cấy ghép'],...['special','destructive','helmet','legs','boots','backpack'].map(id=>[id,'▣',slotName(id)]),['blueprint','▰','Bản vẽ'],['supply','✚','Thuốc & pin'],['material','▤','Vật liệu']];
 const devices=gear.filter(g=>s.inventory.includes(g.id)&&match(g)&&(filter==='all'||filter===g.slot));devices.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name,'vi'):sort==='level'?(a,b)=>b.level-a.level:(a,b)=>itemStats(s,b.id).power-itemStats(s,a.id).power||b.rarity-a.rarity);
 const items=[...materials.map(v=>({...v,type:'material'})),...blueprints.map(v=>({...v,type:'blueprint'})),...supplies.map(v=>({...v,type:'supply',rarity:1}))].filter(v=>bag[v.id]>0&&match(v)&&(filter==='all'||filter===v.type));
 items.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name,'vi')||b.rarity-a.rarity:(a,b)=>b.rarity-a.rarity||a.name.localeCompare(b.name,'vi'));
 return tabs+groupTabs+`<div class="bag-filters">${categories.map(([id,mark,name])=>`<button class="${filter===id?'selected':''}" data-action="bag-filter" data-id="${id}" aria-label="${name}" title="${name}">${mark}</button>`).join('')}</div><div class="bag-search"><input id="search" value="${esc(search)}" placeholder="Tìm vật phẩm…" aria-label="Tìm vật phẩm"><select id="bag-sort" aria-label="Sắp xếp túi đồ"><option value="power" ${sort==='power'?'selected':''}>Sức mạnh</option><option value="level" ${sort==='level'?'selected':''}>Cấp độ</option><option value="name" ${sort==='name'?'selected':''}>Tên A–Z</option></select></div><div class="bag-capacity"><b>Ô: ${bagSize(s)} / ${bagCapacity(s)}</b><small>Mỗi chồng vật phẩm chiếm 1 ô</small></div><div class="bag-rows">${items.map(v=>`<article class="bag-row tier${v.rarity}"><span class="bag-item-icon">${v.icon||'▰'}</span><div><b>${esc(v.name)}${v.type==='blueprint'?' · '+rarities[v.rarity]:''}</b><small>${v.ammo?'Đạn cho vũ khí '+(v.id==='energy-cell'?'đặc biệt':'hủy diệt'):v.id.startsWith('mod-')?'Lắp vào khe trong Chi tiết trang bị':v.type!=='supply'?'Dùng trong Chế tạo':`+${v.hp} HP / +${v.energy} EN`}</small></div><span>×${bag[v.id]}</span>${v.ammo?'':button(v.id.startsWith('mod-')?'Trang bị':v.type!=='supply'?'Chế tạo':'Dùng',v.type!=='supply'?'inventory-tab':'item-use',v.id.startsWith('mod-')?'equipped':v.type!=='supply'?'craft':v.id)}</article>`).join('')}${devices.map(g=>`<article class="bag-row tier${g.rarity}"><input type="checkbox" data-select-gear="${g.id}" aria-label="Chọn ${esc(g.name)}" ${selected.has(g.id)?'checked':''} ${equipped.includes(g.id)?'disabled':''}><span class="bag-item-icon">${icon(g.slot)}</span><button class="bag-gear-link" data-action="detail" data-id="${g.id}"><b>${esc(g.name)}</b><small>LV ${g.level} · PWR ${itemStats(s,g.id).power} ${equipped.includes(g.id)?'· ĐANG MẶC':''}</small></button>${button('Trang bị','equip',g.id,equipped.includes(g.id)||g.level>s.level)}</article>`).join('')}${!items.length&&!devices.length?'<p class="asset-empty">KHÔNG CÓ VẬT PHẨM PHÙ HỢP</p>':''}</div><div class="bag-bulk"><span>Đã chọn ${selected.size} trang bị</span>${button('Bán đã chọn','bulk-sell','',!selected.size)}${button('Tái chế đã chọn','bulk-scrap','',!selected.size)}${button('Bỏ chọn','bag-clear','',!selected.size)}</div><div class="section-label">TIẾP TẾ / CỬA HÀNG TRINOKY</div><div class="supply-shop">${supplies.map(v=>button(`${v.icon} ${v.name} · ${v.price} ₡`,'supply-buy',v.id,s.credits<v.price)).join('')}${ammunition.map(v=>button(`${v.icon} ${v.name} · ${v.price} ₡`,'ammo-buy',v.id,s.credits<v.price)).join('')}</div>`;
}
