import {equipmentSlots,slotLabels} from './gear-rules.js';
import {gear,rarities} from './content.js';
import {bagSize,bagCapacity,ownsGear} from './inventory-state.js';
export function marketListings(world,viewer,{section='browse',query='',slot='all',sort='newest'}={}){
 const q=query.trim().toLocaleLowerCase('vi');return (world?.market||[]).filter(m=>section==='mine'?viewer&&m.seller===viewer:m.seller!==viewer).filter(m=>{const g=gear.find(g=>g.id===m.gear);return g&&(slot==='all'||g.slot===slot)&&`${g.name} ${m.sellerName}`.toLocaleLowerCase('vi').includes(q);}).sort((a,b)=>sort==='cheap'?a.price-b.price:sort==='expensive'?b.price-a.price:(b.time||0)-(a.time||0));
}
export function marketView({s,world,online,esc,button,section='browse',query='',slot='all',sort='newest',draft={id:'',price:'100'}}){
 const mine=section==='mine',blocked=!!s.combat||!!s.dungeon,owned=(world?.market||[]).filter(m=>m.seller===online?.id),items=gear.filter(g=>s.inventory.includes(g.id)&&!Object.values(s.equipped).includes(g.id)),selected=items.some(g=>g.id===draft.id)?draft.id:items[0]?.id||'',list=marketListings(world,online?.id,{section,query,slot,sort});
 const filters=`<div class="market-toolbar"><input id="market-query" type="search" placeholder="Tìm trang bị hoặc người bán…" aria-label="Tìm trong thị trường" value="${esc(query)}"><select id="market-slot" aria-label="Loại trang bị chợ">${[['all','Tất cả loại'],...equipmentSlots.map(id=>[id,slotLabels[id]])].map(([id,label])=>`<option value="${id}" ${slot===id?'selected':''}>${label}</option>`).join('')}</select><select id="market-sort" aria-label="Sắp xếp tin rao">${[['newest','Mới nhất'],['cheap','Giá tăng dần'],['expensive','Giá giảm dần']].map(([id,label])=>`<option value="${id}" ${sort===id?'selected':''}>${label}</option>`).join('')}</select>${button('↻ Cập nhật','market-refresh')}</div>`;
 return `<div class="rail-return">${button('← Trở lại Chợ Neon','nav','bazaar')}</div><div class="market-tabs">${[['browse','Thị trường'],['mine','Gian hàng của tôi']].map(([id,label])=>`<button data-action="market-section" data-id="${id}" class="${section===id?'selected':''}">${label}${id==='mine'?` <small>${online?owned.length+'/10':'—'}</small>`:''}</button>`).join('')}</div><div class="section-label">${mine?'GIAN HÀNG CỦA TÔI':'CHỢ NGƯỜI CHƠI'}<span>${mine?owned.length+'/10':list.length+' TIN RAO'}</span></div><p class="hint">${mine?'Đồ rao được giữ tại chợ. Thu hồi không mất phí; khi túi đầy, đồ chuyển vào hộp thư không hết hạn.':'Giá do người bán đặt. Trang bị chuyển cùng hiệu chuẩn và module; không thu phí giao dịch.'}</p>${!online?`<p class="hint">Đăng nhập để ${mine?'quản lý gian hàng':'mua trang bị'}. Nhân vật khách được lưu riêng.</p>${button('Đăng nhập / tạo tài khoản','auth-open')}`:''}${mine&&online?`<form class="world-form market-compose" data-kind="market-list"><label>Trang bị chưa dùng<select name="id" aria-label="Trang bị rao bán" ${!items.length?'disabled':''}>${items.map(g=>`<option value="${g.id}" ${g.id===selected?'selected':''}>${esc(g.name)} · LV ${g.level}</option>`).join('')||'<option>Không có trang bị khả dụng</option>'}</select></label><label>Giá credits<input name="price" type="number" min="1" max="1000000" value="${esc(draft.price)}" required></label><button ${blocked||!items.length||owned.length>=10?'disabled':''}>Rao bán</button></form>${owned.length>=10?'<p class="travel-lock">Đã đạt giới hạn 10 tin. Thu hồi hoặc bán một món để rao thêm.</p>':''}`:''}${filters}<div class="market-list">${list.map(m=>{const g=gear.find(g=>g.id===m.gear),disabled=!online||blocked||(!mine&&(ownsGear(s,g.id)||bagSize(s)>=bagCapacity(s)||s.credits<m.price||s.level<g.level));return `<article class="market-item tier${g.rarity}"><h3>${esc(g.name)}${m.calibration.level?' +'+m.calibration.level:''}</h3><p>LV ${g.level} · ${rarities[g.rarity]} · ${esc(m.sellerName)}</p><p>Module: ${m.calibration.modules.map(esc).join(', ')||'Trống'}</p><b>${m.price.toLocaleString('vi')} ₡</b>${button(mine?'Thu hồi':'Mua trang bị',mine?'market-cancel':'market-buy',m.id,disabled)}${!mine&&online&&bagSize(s)>=bagCapacity(s)?'<small>Túi đầy; giải phóng một ô trước khi mua.</small>':''}${!mine&&online&&ownsGear(s,g.id)?'<small>Đã sở hữu mẫu này trong túi, kho, chợ hoặc hộp thư.</small>':''}</article>`;}).join('')||`<p class="hint">${!world?'Chưa tải được chợ. Nhấn Cập nhật để thử lại.':mine&&!online?'Đăng nhập để xem các tin của bạn.':query||slot!=='all'?'Không có tin phù hợp với bộ lọc.':mine?'Bạn chưa có tin rao bán.':'Chưa có trang bị từ runner khác.'}</p>`}</div>`;
}
