import {milestones,milestoneStatus,hasKey,pveKills} from './achievements.js';
import {stats} from './game.js';
export function milestonesView({s,esc,button,selected=null}){
 const list=milestones.map(m=>milestoneStatus(s,m.id));
 const meter=m=>`<div class="mission-meter"><i style="width:${m.value/m.target*100}%"></i><b>${m.value} / ${m.target}</b></div>`;
 if(selected){const m=list.find(v=>v.id===selected);if(!m)return '';return `<section class="milestone-detail">${button('‹ Nhiệm vụ thường','close-milestone')}<h1>${m.name}</h1><p>${m.requirement}</p>${m.id==='progression20'?`<p>Cấp: ${s.level} / 20 · Chìa khóa: ${hasKey(s)?'Đã thu':'Chưa có'}</p><p>Di chuyển tới khu vực 20, thách đấu boss hoặc hạ boss trong dungeon ở đó. Boss bị hạ mới được tính.</p>`:'<p>Các bản in từ trước đều được tính. Không cần nhận nhiệm vụ trước khi in.</p>'}${meter(m)}<div class="milestone-reward">+${m.credits} ₡ / +${m.xp} XP / +${m.scrap} linh kiện</div><div class="actions">${button(m.done?'Đã nhận thưởng':'Nhận thưởng','milestone-claim',m.id,m.done||m.value<m.target||!!s.combat||!!s.dungeon)}${button('Đến '+(m.id==='printing'?'máy in':'bản đồ'),'nav',m.destination)}</div></section>`;}
 return `<div class="section-label">THÔNG THƯỜNG <span class="mission-count">${list.filter(m=>!m.done).length}</span></div><div class="milestone-list">${list.map(m=>`<button data-action="milestone-detail" data-id="${m.id}" class="milestone-card ${m.done?'claimed':''}"><b>${m.name}</b><p>Yêu cầu:<br>${m.requirement}</p>${m.id==='printing'?'<em>Sử dụng Máy in 3D để in vật phẩm bất kỳ</em>':`<p>Chìa khóa bí mật Neon: ${hasKey(s)?'Đã thu':'Chưa thu'} · Cấp ${s.level}/20</p>`}${meter(m)}<small>${m.done?'Đã nhận thưởng':'Nhấn để xem chi tiết'}</small></button>`).join('')}</div>`;
}
export function coresView({s,button}){const st=stats(s);return `<div class="section-label">LÕI AI / CÔNG NGHỆ THU HỒI</div><h1 class="city-title">Tái sử dụng tín hiệu.</h1><div class="core-resources"><span>Lõi AI <b>${s.aiCores||0}</b></span><span>Hash <b>${s.hashProcessors||0}</b></span><span>Linh kiện <b>${s.scrap??6}</b></span></div><p class="hint">Mỗi ba địch hoặc boss PvE cho một lõi AI; hiện đã hạ ${pveKills(s)}. Mỗi boss cho thêm một bộ xử lý Hash. Tìm kiếm ở mỗi bản đồ một lần để lấy 1 Hash và 1 linh kiện; tốn 2 EN.</p><article class="core-recipe"><h2>Tìm kiếm khu vực hiện tại</h2><p>${s.scavenged?.includes(s.map)?'Đã tìm kiếm tại khu vực này. Di chuyển tới một bản đồ mới để tiếp tục.':'Thu thập công nghệ còn sót lại tại khu vực đang đứng.'}</p>${button('Lục tìm · 2 EN','scavenge','',!!s.combat||!!s.dungeon||s.energy<2||s.scavenged?.includes(s.map))}</article><article class="core-recipe"><h2>Chế tạo lõi AI</h2><p>2 bộ xử lý Hash + 3 linh kiện → 1 lõi AI.</p>${button('Chế tạo','core-craft','',!!s.combat||!!s.dungeon||(s.hashProcessors||0)<2||(s.scrap??6)<3)}</article><article class="core-recipe"><h2>Tiếp năng lượng</h2><p>1 lõi AI → hồi 20 EN và 30 HP. Không vượt giới hạn, chỉ dùng ngoài giao tranh/dungeon.</p>${button('Dùng lõi AI','core-recharge','',!!s.combat||!!s.dungeon||(s.aiCores||0)<1||s.energy>=30&&s.hp>=st.maxHp)}</article>`;}
