import {stations,stationPlan} from './rail.js';
import {keysView} from './keys-view.js';
export function railView({s,station,esc,button}){
 const plan=stationPlan(s,station);
 const hero=`<div class="rail-banner"><img src="/src/rail.svg" alt="Ga tàu Neon với đường ray phát sáng và những runner chờ tàu"><div><h1>${plan?esc(plan.name):'Ga tàu trung tâm'}</h1><p>${plan?`Tuyến khu vực cấp ${plan.from} đến ${plan.to}. Chọn điểm đến để tiếp tục hành trình.`:'Mạng Hyperloop nối năm tuyến khắp thành phố. Du hành tốn 1 EN; mở khu vực cao hơn tối đa 2 cấp.'}</p><span>Phiêu lưu</span></div></div>`;
 const back=`<div class="rail-return">${button('← '+(plan?'Trở lại ga tàu trung tâm':'Trở lại Trung tâm TP. Neon'),plan?'rail-back':'nav',plan?'':'hub')}</div>`;
 if(plan)return back+hero+`<div class="section-label">DU HÀNH <span>LV ${plan.from}–${plan.to}</span></div><div class="city-travel-list">${plan.maps.map(m=>{const blocked=m.level>s.level+2||!plan.can||s.map===m.id;return `<button class="city-travel ${blocked?'rail-locked':''}" data-action="move" data-id="${m.id}" ${blocked?'disabled':''}><span class="travel-icon">♧</span><div><b>${esc(m.name)}</b><p>Cấp ${m.level} · ${esc(m.faction)}</p>${s.map===m.id?'<small>Đang ở đây</small>':m.level>s.level+2?`<p class="travel-lock">Cần cấp ${Math.max(1,m.level-2)}</p>`:''}</div></button>`;}).join('')}</div>${plan.missing.map(v=>`<p class="travel-lock">${esc(v)}</p>`).join('')}${button('Khám phá khu vực hiện tại','nav','terminal')}`;
 return back+hero+`<div class="section-label">DU HÀNH / NĂM TUYẾN</div><div class="city-travel-list">${stations.map(v=>{const p=stationPlan(s,v.id);return `<button class="city-travel ${p.can?'':'rail-locked'}" data-action="rail-station" data-id="${v.id}" ${p.can?'':'disabled'}><span class="travel-icon">♧</span><div><b>ĐẾN ${esc(v.name.toUpperCase())}</b><p>Cấp ${v.from} đến ${v.to}</p>${p.missing.map(t=>`<p class="travel-lock">${esc(t)}</p>`).join('')}</div></button>`;}).join('')}</div>${keysView(s,esc,button)}<div class="section-label">TRUNG TÂM</div><div class="rail-return">${button('← Trở lại Trung tâm TP. Neon','nav','hub')}</div>`;
}
