import {equipmentSlots,slotLabels} from './gear-rules.js';
import {cityIcon} from './city-icons.js';
import {navIcon} from './ui-shell.js';
import {gear,maps} from './content.js';
import {resources,printing,printPlan,calibrationPlan} from './services.js';

export function serviceView({s,tab,esc,button,gearCard,options,calibrationId,financeAmount=1,world=null,online=null}){
 const r=resources(s);
 const banner=(kind,title,name,quote)=>`<div class="merchant service-banner ${kind}"><img src="/src/${kind==='city'?'city':'laboratory'}.svg" alt="${kind==='city'?'Thành phố cyberpunk về đêm':'Xưởng công nghệ với máy in và cánh tay robot'}"><div class="merchant-title"><span>${kind==='city'?'CENTRAL HUB / SECTOR 01':'HELIX ENGINEERING / LAB 09'}</span><h1>${title}</h1></div><div class="merchant-dialogue"><b>${name}</b><p>${quote}</p></div></div>`;
 if(tab==='hub'){
 const destinations=[['exchange','◇','Cửa hàng Unit Helix'],['cosmetics','▣','Hiệu ứng cyberwear'],['printer','⬡','Máy in 3D'],['shop','⌁','Xưởng chế tác'],['medical','✚','Cửa hàng Trinoky'],['terminal','>_','Bảng điều khiển'],['rewards','◇','Tiếp tế hằng ngày'],['bank','▥','Ngân hàng Helix'],['market','▣','Cửa hàng runner'],['station','⚒','Trạm hiệu chuẩn']];
 const member=online&&world?.corporation,coast=maps[1];
 const travel=(id,icon,title,description,badge,lock='')=>`<button class="city-travel" data-action="nav" data-id="${id}"><span class="travel-icon">${cityIcon({rail:'clock',commercial:'clock',bazaar:'stall',headquarters:'group',corporation:'group',housing:'house',coast:'coast',dungeon:'alley'}[id])}</span><div><b>${title}</b><p>${description}</p>${lock?`<p class="travel-lock">${lock}</p>`:''}<small>${badge}</small></div></button>`;
 return `<div class="merchant service-banner city city-center"><img src="/src/city.svg" alt="Thành phố Neon với cầu đi bộ, biển đèn và những tòa nhà về đêm"><div class="city-overlay"><div class="eyebrow">THÀNH PHỐ TRO / CENTRAL HUB</div><h1>Trung tâm TP. Neon</h1><p>Một trong những thành phố nhộn nhịp nhất lục địa. Gặp các runner, tìm thiết bị và chuẩn bị chuyến đi tiếp theo.</p><div class="city-quick-actions">${button(s.dungeon?'Tiếp tục phó bản':'Vào phó bản','nav','dungeon')}${button('Nhiệm vụ','nav','missions')}</div></div></div><div class="section-label">CÓ THỂ TƯƠNG TÁC</div><div class="hub-actions">${destinations.map(([id,icon,label])=>`<button data-action="nav" data-id="${id}" class="${['exchange','cosmetics'].includes(id)?'highlight':''}"><span>${navIcon(id)}</span>${label}</button>`).join('')}</div><div class="section-label">DU HÀNH</div><div class="city-travel-list">${travel('rail','♧','Đến ga tàu trung tâm','Mạng Hyperloop nối năm tuyến cấp 1–50. Thu thập mảnh khóa để ghép khóa Vành Đai và Thiên Đỉnh tại Terminal.','Phiêu lưu')}${travel('commercial','◷','Đến khu thương mại Neon','Nơi đầy các shop và doanh nghiệp. Nhận hợp đồng hoặc bồi dưỡng nghề in trang bị.','Trung tâm công việc')}${travel('bazaar','▥','Đến chợ Neon','Gian hàng của người chơi. Mua và bán trang bị cùng những runner khác.','Thị trường người chơi')}${travel(member?'headquarters':'corporation','♙','Đến trụ sở tập đoàn','Trụ sở của bạn và các thành viên nhóm. Gặp những runner cùng tập đoàn.','Đội',member?'':'Bạn phải gia nhập tập đoàn để vào trụ sở. Nhấn để tìm hoặc thành lập nhóm.')}${travel('housing','▦','Đi về căn hộ của bạn','Căn hộ giữa trung tâm thành phố, nơi nghỉ ngơi và lưu trữ trang bị.','Nhà',s.housing?'':s.level<100?'Bạn cần đạt cấp 100 để thuê căn hộ.':'Thuê với phí một lần 2.500 credits.')}${travel('coast','≈','Đi đến khu vực bờ biển','Bến cảng cách trung tâm vài km. Ngắm đường chân trời rồi tiếp tục khám phá Cảng Tro.','Bờ biển')}${travel('dungeon','Ω',s.dungeon?'Tiếp tục dungeon':'Đến cửa dungeon','Khám phá mê cung ký tự, mở rương và hạ boss qua ba tầng.','Dungeon PvE')}</div><p class="hint">Vị trí nhân vật: ${esc(maps.find(m=>m.id===s.map).name)}. Các dịch vụ trung tâm có thể xem từ mọi khu vực.</p>`;
 }
 if(tab==='printer'){const p=printing(s);return banner('printer','Máy in phân tử','NIA / KỸ SƯ IN','Không có bản in miễn phí. Mang đủ linh kiện, tôi sẽ lo phần còn lại.')+`<div class="section-label">IN TRANG BỊ <span>${r.scrap} LINH KIỆN</span></div><div class="profession"><div><b>CẤP NGHỀ IN ${p.rank}</b><span>${p.xp} / ${p.rank*50} XP</span></div><div class="quality-track"><i style="width:${Math.min(100,p.xp/(p.rank*50)*100)}%"></i></div><p>In trang bị đến cấp ${Math.min(50,p.rank+2)}. Mỗi bản in tăng 25 XP nghề. Đồ cấp cao vẫn yêu cầu cấp nhân vật tương ứng để trang bị.</p></div><div class="print-recipes">${equipmentSlots.map(slot=>{const name=slotLabels[slot];return [slot,name];}).map(([slot,name])=>{const plan=printPlan(s,slot),can=!s.combat&&s.credits>=plan.cost&&r.scrap>=2&&plan.pool.length;return `<article class="print-recipe"><h2>◈ ${name}</h2><dl><dt>Cần</dt><dd>2 linh kiện / ${plan.cost} ₡</dd><dt>Nhận</dt><dd>1 trang bị chưa sở hữu / +25 XP nghề in</dd></dl><p>${plan.pool.length} mẫu khả dụng · ${can?'Sẵn sàng in':plan.pool.length?'Cần thêm tài nguyên hoặc kết thúc giao tranh':'Đã sở hữu mọi mẫu ở cấp nghề hiện tại'}</p>${button('In '+name.toLowerCase(),'print',slot,!can)}</article>`;}).join('')}</div><p class="hint">Địch thường cho 1 linh kiện, boss cho 3. Sáu linh kiện khởi đầu giúp bạn thử máy in.</p>`;}
 if(tab==='station'){const eligible=gear.filter(g=>s.inventory.includes(g.id));const g=eligible.find(g=>g.id===calibrationId)||eligible[0];if(!g)return banner('station','Trạm hiệu chuẩn','ARI / KỸ SƯ HIỆU CHUẨN','Chọn món đồ bạn muốn giữ lại cùng mình.')+'<p class="hint">Bạn chưa có trang bị. Mua hoặc in một món trước.</p>'+button('Đến shop','nav','shop');const plan=calibrationPlan(s,g.id,options);return banner('station','Trạm hiệu chuẩn','ARI / KỸ SƯ HIỆU CHUẨN','Tôi có thể đẩy thiết bị xa hơn giới hạn. Hãy kiểm tra rủi ro trước khi bật máy.')+`<div class="station-options"><label><input id="boost-calibration" type="checkbox" ${options.boost?'checked':''}> Tăng thành công +10% <small>1 Unit</small></label><label><input id="protect-calibration" type="checkbox" ${options.protect?'checked':''}> Ngăn phá hủy <small>2 Unit</small></label></div><div class="station-probabilities"><div><small>NGUY CƠ PHÁ HỦY</small><strong>${(plan.destruction*100).toFixed(1)}%</strong></div><div><span>THÀNH CÔNG ${(plan.success*100).toFixed(1)}%</span><small>Thất bại giữ đồ: ${(plan.failure*100).toFixed(1)}%</small><small>${r.units} Unit hiện có</small></div></div><p class="risk-note">${plan.destruction>0?'Có thể mất vĩnh viễn trang bị và module. Bật bảo vệ để loại bỏ nguy cơ này.':'Không có nguy cơ mất trang bị với lựa chọn hiện tại.'} Thất bại vẫn tiêu thụ credits và Unit. Hiệu chuẩn tại trạm có phí thấp hơn nâng cấp bảo đảm trong chi tiết trang bị.</p><label class="station-select">CHỌN TRANG BỊ<select id="calibration-item">${eligible.map(item=>`<option value="${item.id}" ${item.id===g.id?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>${gearCard(g)}<div class="station-capacity"><span>NĂNG LỰC HIỆU CHUẨN</span><div class="calibration-boxes">${Array.from({length:5},(_,i)=>`<i class="${i<plan.level?'filled':''}"></i>`).join('')}</div></div><div class="calibration-preview"><div class="section-label">CHỈ SỐ KHI THÀNH CÔNG <span>+${plan.level} → +${Math.min(5,plan.level+1)}</span></div><div><span>Sức mạnh</span><b>+${plan.before.power}</b><i>→</i><b>+${plan.after.power}</b><em>+2</em></div><div><span>Chất lượng</span><b>${plan.before.quality}%</b><i>→</i><b>${plan.after.quality}%</b><em>+${plan.after.quality-plan.before.quality}%</em></div></div><p class="hint">Phí: ${plan.cost} ₡ + ${plan.units} Unit · Nâng tối đa +5 · Module đang lắp được giữ khi thành công.</p>${button('⚒ Hiệu chuẩn · '+plan.cost+' ₡','calibrate',g.id,!!s.combat||g.level>s.level||plan.level>=5||s.credits<plan.cost||r.units<plan.units)}`;}
 if(tab==='exchange')return banner('city','Unit Helix','TIỀN TỆ NẠP','Unit dùng để bỏ qua hàng chờ và bảo vệ trang bị khi hiệu chuẩn.')+`<div class="section-label">SỐ DƯ <span>${r.units} UNIT</span></div><div class="profession"><b>${r.units} UNIT</b><p>Unit chỉ có từ nạp. Credits, nhiệm vụ và vật phẩm không đổi được sang Unit.</p></div><article class="card"><h3>Nạp Unit</h3><p>Hiện nạp được xử lý thủ công: liên hệ quản trị viên để được hướng dẫn và xác nhận giao dịch. Unit được cộng vào tài khoản sau khi admin xác nhận.</p><p class="hint">Cổng thanh toán tự động chưa được cấu hình. Tài khoản mới bắt đầu với 0 Unit; cần đăng nhập để nhận Unit đã nạp.</p></article><div class="actions">${button('Công việc & hàng chờ','nav','commercial')}${button('Trạm hiệu chuẩn','nav','station')}${!online?button('Đăng nhập','auth-open'):''}</div>`;
 if(tab==='bank')return banner('city','Ngân hàng Helix','KHO LƯU TRỮ AN TOÀN','Credits gửi tại đây không bị mất khi thất bại trong chiến đấu.')+`<div class="section-label">SỐ DƯ <span>${s.credits} ₡ / ${r.units} UNIT</span></div><div class="profession"><b>${r.bank} ₡ TRONG KÉT</b></div><form id="finance-form" data-kind="bank"><label>Số lượng credits<input name="amount" type="number" min="1" max="1000000000" step="1" value="${esc(financeAmount)}" required></label><div class="actions"><button name="direction" value="deposit" ${s.combat?'disabled':''}>Gửi credits</button><button name="direction" value="withdraw" ${s.combat?'disabled':''}>Rút credits</button></div></form>`;
 return '';
}
