import {cityIcon} from './city-icons.js';
import {jobs,workPlan,workRemaining,workSkipPlan} from './work.js';
import {printing} from './services.js';
import {craftSkill} from './crafting.js';
export const duration=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;
export function workPanel(s,button,esc){
 if(!s.work)return '';const j=jobs.find(v=>v.id===s.work.id),p=workSkipPlan(s),remaining=p.remaining;
 const elapsed=Math.max(0,Math.min(100,(Date.now()-s.work.startedAt)/Math.max(1,s.work.endsAt-s.work.startedAt)*100));
 const skip=button(`Dùng ${p.cost} Unit & nhận thưởng`,'work-skip',p.key,!p.can).replace('<button ',`<button data-cost="${p.cost}" `);
 return `<section class="work-progress" aria-label="Công việc hiện tại"><b>${esc(j?.name||s.work.id)} ×${s.work.count||1}</b><p data-work-clock>${remaining?'Còn '+duration(remaining):'Hoàn thành · có thể nhận thưởng'}</p><div class="bar"><i data-work-bar style="width:${elapsed}%"></i></div><div class="actions">${button('Nhận thưởng','work-claim','',remaining>0)}${button('Hủy công việc','work-cancel')}</div><details class="work-skip" data-ui-panel="work-skip-${esc(p.key)}"><summary>Bỏ qua hàng chờ · <span data-work-skip-cost>${p.cost}</span> Unit</summary><p>Hoàn thành và nhận thưởng ngay. Phí 1 Unit / phút còn lại, làm tròn lên; phí giảm theo thời gian còn lại.</p><p>Số dư: <b>${p.units} Unit</b> · Chỉ có từ nạp.</p><p class="hint" data-work-skip-note>${remaining?(p.can?'Xác nhận bên dưới để dùng Unit.':'Không đủ Unit. Bạn có thể tiếp tục chờ miễn phí.'):'Công việc đã xong. Nhận thưởng miễn phí.'}</p>${skip}</details><small>Hủy không hoàn lại tài nguyên đã dùng. Phần thưởng chờ bạn nhận sau khi quay lại.</small></section>`;
}
export function commercialView({s,esc,button}){const p=printing(s),m=craftSkill(s,'medical'),a=craftSkill(s,'ammo');return `<div class="rail-return">${button('← Trở lại Trung tâm TP. Neon','nav','hub')}</div><div class="commercial-banner"><img src="/src/commercial.svg" alt="Khu thương mại Neon với phố công nghệ và người lao động"><div><h1>Khu Thương Mại Neon</h1><p>Các xưởng công nghệ và mạng dữ liệu mở cơ hội đào tạo, nâng nghề và kiếm credits.</p><span>Trung tâm công việc</span></div></div>${workPanel(s,button,esc)}<div class="section-label">HÀNH ĐỘNG</div><div class="work-list">${jobs.filter(j=>!j.area).map(j=>{const v=workPlan(s,j.id);return `<article class="work-card ${j.id==='mine'?'work-income':''}"><span class="work-icon">${cityIcon({printing:'print',medical:'medical',ammo:'ammo',recycle:'recycle',mine:'mine'}[j.id])}</span><div><h2>${esc(j.name.toUpperCase())}</h2><p>${esc(j.description)}</p><small>${j.seconds} giây · ${j.energy} EN${j.scrap?' · 1 linh kiện':''} · ${j.xp?`+${j.xp} XP nghề`:`+${v.credits} ₡`}</small>${v.missing.map(t=>`<p class="travel-lock">${esc(t)}</p>`).join('')}<div class="work-start">${button('Chọn số lượt','work-prepare',j.id,!!s.work||!!s.combat||!!s.dungeon)}</div></div></article>`;}).join('')}</div><div class="section-label">TIẾN TRÌNH NGHỀ</div><div class="work-skills">${[['In ấn',p,50,50],['Y học',m,100,40],['Đạn dược',a,100,40]].map(([name,v,cap,step])=>`<div><b>${name} · LV ${v.rank}/${cap}</b><p>${v.xp}/${v.rank*step} XP</p><div class="bar"><i style="width:${Math.min(100,v.xp/(v.rank*step)*100)}%"></i></div></div>`).join('')}</div><p class="hint">Chỉ một công việc mỗi lần. Công việc tạm khóa di chuyển, chiến đấu, nghỉ và chế tạo đến khi nhận thưởng hoặc hủy. XP đào tạo không tính là vật phẩm đã in hay đã chế tạo.</p><div class="actions">${button('Máy in 3D','nav','printer')}${button('Chế tạo','inventory-tab','craft')}${button('Nhiệm vụ','nav','missions')}${button('Chợ đen','nav','black')}</div>`;}
