import {afkBoostPanel} from './afk-view.js';
import {marketView} from './market-view.js';
import {gear} from './content.js';
import {cosmetics,housingLevel,housingPrice} from './city.js';
import {stats} from './game.js';
const pct=(value,target)=>Math.min(100,Math.floor(value/target*100));
export function communityView({world,s,online,esc,button}){
 if(!world)return '<p class="hint">Chưa tải được dữ liệu cộng đồng.</p>';
 const row=(name,total,target,color,extra)=>`<article class="community-goal ${color}"><div class="goal-heading"><h2>${name}</h2><b>${total.toLocaleString('vi')} / ${target.toLocaleString('vi')}</b></div><div class="goal-track"><i style="width:${pct(total,target)}%"></i></div><span class="goal-percent">${pct(total,target)}%</span>${extra}</article>`;
 return afkBoostPanel({s,world,online,esc,button})+`<div class="community-section"><div class="section-label">MỤC TIÊU CỘNG ĐỒNG <span>${esc(world.day)} / UTC+7</span></div>${row('Rò rỉ dữ liệu Neon',world.kills,10000,'pink','<p>Hạ địch và boss PvE để thu thập dữ liệu. Tiến trình cộng dồn từ các tài khoản trên server.</p>')}${world.funds.map(f=>row(esc(f.name),f.total,f.target,f.id==='global'?'yellow':f.id==='morning'?'blue':'lime',`<div class="goal-contributors">${f.contributors.map(c=>`<span>${esc(c.name)} <b>${c.value.toLocaleString('vi')} ₡ · ${pct(c.value,f.target)}%</b></span>`).join('')||'<small>Chưa có đóng góp</small>'}<strong>${f.active?'ĐANG ÁP DỤNG':f.total>=f.target?'CHỜ GIỜ':'MỤC TIÊU'} · ${f.discount}% OFF</strong></div><p>Đủ quỹ: giảm ${f.discount}% giá shop ${f.hour?'từ '+String(f.hour).padStart(2,'0')+':00':'ngay lập tức'} đến hết ngày Việt Nam. Quỹ bắt đầu lại lúc 00:00.</p><form class="world-form donation-form" data-kind="donate" data-id="${f.id}"><input name="amount" type="number" min="1" max="${Math.max(1,f.target-f.total)}" placeholder="Credits đóng góp" aria-label="Đóng góp ${esc(f.name)}" required><button ${!online||s.combat||s.dungeon||f.total>=f.target?'disabled':''}>Đóng góp</button></form>`)).join('')}<p class="hint">Giảm giá đang có: ${Math.round(world.discount*100)}%. Áp dụng cho tài khoản online tại shop thường và chợ đen; không áp dụng cho giao dịch giữa người chơi.${!online?' Đăng nhập để đóng góp.':''}</p></div>`;
}
export function guidanceView(button){return `<div class="section-label">KHÁC <span>HƯỚNG DẪN RUNNER</span></div><div class="guidance-list">${[['printer','Nhận thiết bị tốt hơn!','In trang bị mới bằng linh kiện. Cấp nghề tăng theo số bản in.'],['station','Nâng cấp thiết bị vĩnh viễn!','Hiệu chuẩn tăng sức mạnh. Kiểm tra nguy cơ phá hủy và dùng Unit để bảo vệ.'],['cores','Có được lõi AI','Lục tìm ở nhiều khu vực, chế tạo từ Hash và linh kiện hoặc nhặt từ địch PvE.'],['reputation','Tặng danh tiếng','Tặng người chơi khác 1 uy tín để thể hiện sự kính trọng hoặc lòng biết ơn.']].map(([id,title,text])=>`<button class="guidance" data-action="nav" data-id="${id}"><b>${title}</b><p>${text}</p><small>Nhấn để mở →</small></button>`).join('')}</div>`;}
export function worldView({s,tab,world,online,esc,button,marketSection,marketQuery,marketSlot,marketSort,marketDraft}){
 const locked=!online,blocked=!!s.combat||!!s.dungeon;
 const login=locked?`<p class="hint">Đăng nhập để sử dụng dịch vụ cộng đồng. Tiến trình khách được giữ riêng.</p>${button('Đăng nhập / tạo tài khoản','nav','account')}`:'';
 if(tab==='market')return marketView({s,world,online,esc,button,section:marketSection,query:marketQuery,slot:marketSlot,sort:marketSort,draft:marketDraft});
 if(tab==='corporation'||tab==='headquarters'){const corp=world?.corporations.find(c=>c.id===world.corporation);if(corp)return `<div class="section-label">TRỤ SỞ TẬP ĐOÀN <span>${corp.members.length} / 20 RUNNER</span></div><h1 class="city-title">${esc(corp.name)}</h1><p class="hint">Trụ sở chung của các thành viên. Người đứng đầu sẽ chuyển cho thành viên còn lại khi rời tập đoàn.</p><div class="corporation-roster">${corp.members.map(m=>`<article><b>${esc(m.name)}</b><span>Cấp ${m.level} ${m.id===corp.leader?'· Đứng đầu':''}</span></article>`).join('')}</div>${button('Rời tập đoàn','corp-leave','',blocked)}`;return `<div class="section-label">TẬP ĐOÀN <span>NHÓM RUNNER</span></div><p class="hint">Gia nhập miễn phí hoặc lập tập đoàn với 500 credits. Tối đa 20 thành viên. Gia nhập để mở trụ sở.</p><form class="world-form" data-kind="corp-create"><input name="text" minlength="3" maxlength="32" placeholder="Tên tập đoàn" aria-label="Tên tập đoàn" required><button ${locked||blocked||s.credits<500?'disabled':''}>Thành lập · 500 ₡</button></form>${login}<div class="market-list">${world?.corporations.map(c=>`<article class="market-item"><h3>${esc(c.name)}</h3><p>${c.members.length} / 20 thành viên</p>${button('Gia nhập','corp-join',c.id,locked||blocked||c.members.length>=20)}</article>`).join('')||'<p class="hint">Chưa có tập đoàn.</p>'}</div>`;}
 if(tab==='housing'){const h=s.housing;return `<div class="section-label">CĂN HỘ NEON <span>${h?'ĐÃ THUÊ':'CẤP '+housingLevel}</span></div><h1 class="city-title">Một nơi để trở về.</h1><p class="hint">Mở ở cấp ${housingLevel}. Phí thuê một lần ${housingPrice.toLocaleString('vi')} credits; hồi phục miễn phí và kho 20 món. Trang bị trong kho giữ nâng cấp nhưng không thể sử dụng đến khi lấy ra.</p>${!h?button(s.level<housingLevel?'Cần đạt cấp '+housingLevel:'Thuê căn hộ · 2.500 ₡','housing-rent','',blocked||s.level<housingLevel||s.credits<housingPrice):button('Nghỉ tại căn hộ','housing-rest','',blocked)+`<div class="section-label">TÚI ĐỒ → KHO <span>${h.storage.length}/20</span></div><div class="storage-list">${s.inventory.filter(id=>!Object.values(s.equipped).includes(id)).map(id=>`<div><span>${esc(gear.find(g=>g.id===id).name)}</span>${button('Cất đồ','housing-deposit',id,blocked||h.storage.length>=20)}</div>`).join('')||'<p class="hint">Không có đồ chưa trang bị.</p>'}</div><div class="section-label">KHO → TÚI ĐỒ</div><div class="storage-list">${h.storage.map(id=>`<div><span>${esc(gear.find(g=>g.id===id).name)}</span>${button('Lấy đồ','housing-withdraw',id,blocked)}</div>`).join('')||'<p class="hint">Kho đang trống.</p>'}</div>`}`;}
 if(tab==='medical')return `<div class="section-label">TRINOKY / TRẠM Y TẾ</div><h1 class="city-title">Khôi phục sinh lực.</h1><p class="hint">Điều trị ngoài giao tranh. Hồi đầy HP với 15 credits; không hồi năng lượng. Bạn cũng có thể nghỉ miễn phí tại Terminal.</p><p>${s.hp} / ${stats(s).maxHp} HP</p>${button('Điều trị · 15 ₡','medical','',blocked||s.credits<15||s.hp>=stats(s).maxHp)} ${button('Đến Terminal','nav','terminal')}`;
 if(tab==='cosmetics')return `<div class="section-label">HIỆU ỨNG CYBERWEAR <span>TRANG TRÍ HỒ SƠ</span></div><p class="hint">Đổi màu viền chân dung và huy hiệu cấp. Hiệu ứng không tăng chỉ số; mua một lần, đổi lại miễn phí.</p><div class="cosmetic-list">${cosmetics.map(c=>`<article style="--aura:${c.color}"><span class="aura-preview">◈</span><h3>${c.name}</h3>${button(s.aura===c.id?'Đang bật':s.cosmetics?.includes(c.id)?'Bật hiệu ứng':`Mua · ${c.price} ₡`,'cosmetic',c.id,blocked||s.aura===c.id||!s.cosmetics?.includes(c.id)&&s.credits<c.price)}</article>`).join('')}</div>`;
 return '';
}
